import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { getRepositoryToken } from '@nestjs/typeorm';
import { Repository, In } from 'typeorm';
import { AppModule } from './src/app.module';
import { SpatialService } from './src/spatial/spatial.service';
import { HistoricalComparisonService } from './src/historical-imagery/historical-comparison.service';
import { WorkflowsService } from './src/workflows/workflows.service';
import { AuditService } from './src/audit/audit.service';
import { RestrictionZone } from './src/spatial/restriction-zone.entity';
import { Parcel } from './src/parcels/parcel.entity';
import { CitizenParcel } from './src/parcels/citizen-parcel.entity';
import { User } from './src/users/user.entity';
import { CURRENT_YEAR } from './src/common/parcel-generation/parcel-category';
import { CLUSTER_CONFIGS } from './src/common/parcel-generation/cluster-generator';

// Populates two things a fresh reseed always leaves empty, using the app's
// REAL business logic end to end (not hand-typed rows) - per the user's
// explicit "dont create mock data instead write some logic for this":
//
// 1. Governance alerts - regenerated by re-running the exact real pipelines
//    that create them (SpatialService.createRestrictionZone's real
//    point-in-polygon overlap check, HistoricalComparisonService.compare's
//    real 2025->2026 category-change diff). seed.ts inserts the flood
//    RestrictionZone and every cluster's historical snapshots/state rows
//    directly via repository.save (by design - see governance-alert.entity.ts
//    and change-detection.service.ts's comments), so nothing has ever
//    actually called the code that turns that real geometry/history into an
//    alert. This script is that missing call, safe to re-run after any
//    reseed.
// 2. Demo service requests (Workflow rows) - genuinely synthetic (no citizen
//    has actually filed one yet in this demo environment), but built through
//    the real WorkflowsService.create()/reviewStep() so routing, steps,
//    notifications, and audit logging all happen exactly as they would for a
//    real citizen - only the "who filed this and why" is invented, matching
//    what the user approved mock data for.
async function main() {
  const app = await NestFactory.createApplicationContext(AppModule, { logger: ['error', 'warn'] });

  try {
    await regenerateZoneOverlapAlerts(app);
    await runHistoricalComparisons(app);
    await seedDemoRequests(app);
  } finally {
    await app.close();
  }
}

// The flood RestrictionZone's geometry and district/state were computed for
// real at seed time (a real point-in-polygon pass over every Pune parcel's
// centroid), but saved directly - createOverlapAlerts (the code that turns
// "these parcels are really inside this zone" into a GovernanceAlert) never
// ran for it. Deleting and recreating it through the real
// createRestrictionZone() re-derives affectedParcelIds itself and fires that
// same alert-creation logic for real, rather than duplicating its wording
// here.
async function regenerateZoneOverlapAlerts(app: Awaited<ReturnType<typeof NestFactory.createApplicationContext>>) {
  const spatialService = app.get(SpatialService);
  const zoneRepository = app.get<Repository<RestrictionZone>>(getRepositoryToken(RestrictionZone));

  const zones = await zoneRepository.find();
  let alertsBefore = 0;
  for (const zone of zones) {
    const { name, restrictionType, stateCode, district, geometry } = zone;
    await zoneRepository.delete({ id: zone.id });
    await spatialService.createRestrictionZone({
      name,
      restrictionType,
      stateCode,
      district,
      geometry: JSON.parse(geometry),
    });
    alertsBefore += 1;
  }
  console.log(`Re-created ${alertsBefore} restriction zone(s) through the real overlap pipeline (RESTRICTION_ZONE_OVERLAP alerts generated for every genuinely-affected parcel).`);
}

// HistoricalComparisonService.compare() only ever accepts 2025 -> 2026 (the
// one comparison allowed to create alerts, enforced inside the service
// itself) and needs both years' ClusterHistoricalSnapshot rows to exist -
// every cluster gets those at seed time, so this runs for all of them, not
// just Pune.
async function runHistoricalComparisons(app: Awaited<ReturnType<typeof NestFactory.createApplicationContext>>) {
  const historicalComparisonService = app.get(HistoricalComparisonService);

  for (const cluster of CLUSTER_CONFIGS) {
    try {
      const result = await historicalComparisonService.compare(cluster.clusterId, CURRENT_YEAR - 1, CURRENT_YEAR);
      console.log(
        result.changeDetected
          ? `Historical comparison for ${cluster.clusterId}: ${result.affectedParcels.length} parcel(s) changed category between ${CURRENT_YEAR - 1} and ${CURRENT_YEAR} - real DISPUTE_DETECTED/RESTRICTION_DETECTED alerts created.`
          : `Historical comparison for ${cluster.clusterId}: no category change between ${CURRENT_YEAR - 1} and ${CURRENT_YEAR}.`,
      );
    } catch (err) {
      console.warn(`Historical comparison for ${cluster.clusterId} skipped: ${(err as Error).message}`);
    }
  }
}

const OFFICER_ROLE_BY_DEPARTMENT: Record<string, string> = {
  LAND_RECORDS: 'LAND_RECORD_OFFICER',
  REGISTRATION: 'REGISTRATION_OFFICER',
  PLANNING: 'PLANNING_OFFICER',
  DISPUTE: 'DISPUTE_OFFICER',
};

interface PlannedRequest {
  citizen: User;
  parcelId: string;
  workflowType: string;
  requestDetails: string;
  // How far to advance it after filing - undefined leaves it untouched (SUBMITTED).
  decisions?: Array<'APPROVE' | 'REJECT'>;
}

async function seedDemoRequests(app: Awaited<ReturnType<typeof NestFactory.createApplicationContext>>) {
  const workflowsService = app.get(WorkflowsService);
  const auditService = app.get(AuditService);
  const userRepository = app.get<Repository<User>>(getRepositoryToken(User));
  const parcelRepository = app.get<Repository<Parcel>>(getRepositoryToken(Parcel));
  const citizenParcelRepository = app.get<Repository<CitizenParcel>>(getRepositoryToken(CitizenParcel));

  const officersByRole = new Map((await userRepository.find({ where: { role: In(Object.values(OFFICER_ROLE_BY_DEPARTMENT)) } })).map((o) => [o.role, o]));

  const citizens = await userRepository.find({ where: { role: 'CITIZEN' }, order: { email: 'ASC' } });
  const links = await citizenParcelRepository.find({ relations: ['citizen', 'parcel'] });
  const ownedParcelIdsByCitizen = new Map<string, string[]>();
  const claimedParcelIds = new Set<string>();
  for (const link of links) {
    claimedParcelIds.add(link.parcel.id);
    const list = ownedParcelIdsByCitizen.get(link.citizen.id) ?? [];
    list.push(link.parcel.id);
    ownedParcelIdsByCitizen.set(link.citizen.id, list);
  }

  const allParcels = await parcelRepository.find();
  const unclaimedParcelIds = allParcels.filter((p) => !claimedParcelIds.has(p.id)).map((p) => p.id);
  const citizensWithParcels = citizens.filter((c) => (ownedParcelIdsByCitizen.get(c.id)?.length ?? 0) > 0);

  if (citizensWithParcels.length < 8 || unclaimedParcelIds.length < 3) {
    console.warn(
      `Not enough seeded data to build a full demo request set (${citizensWithParcels.length} citizens with a parcel, ${unclaimedParcelIds.length} unclaimed parcels) - skipping demo requests.`,
    );
    return;
  }

  const ownedPick = (i: number) => {
    const citizen = citizensWithParcels[i % citizensWithParcels.length];
    const parcelId = ownedParcelIdsByCitizen.get(citizen.id)![0];
    return { citizen, parcelId };
  };

  const plans: PlannedRequest[] = [
    // Document-request types, on the citizen's own parcel - a spread across
    // "just filed", "one department signed off", "fully approved", "rejected
    // at the first department" so the officer/citizen Requests pages show
    // every real status a workflow can be in.
    {
      ...ownedPick(0),
      workflowType: 'ROR_COPY_REQUEST',
      requestDetails: 'Requesting a certified copy of the Record of Rights (RoR) for this parcel - needed to support a bank loan application.',
    },
    {
      ...ownedPick(1),
      workflowType: 'ROR_COPY_REQUEST',
      requestDetails: 'Requesting a certified RoR copy for this parcel for a pending property sale.',
      decisions: ['APPROVE'],
    },
    {
      ...ownedPick(2),
      workflowType: 'CORRECTION_REQUEST',
      requestDetails: 'The owner name recorded against this parcel is misspelled on the current record; requesting a correction to match my government ID.',
      decisions: ['APPROVE', 'APPROVE', 'APPROVE'],
    },
    {
      ...ownedPick(3),
      workflowType: 'CORRECTION_REQUEST',
      requestDetails: 'The area recorded for this parcel does not match the figure on my original survey document; requesting a correction after re-verification.',
      decisions: ['REJECT'],
    },
    {
      ...ownedPick(4),
      workflowType: 'DOCUMENT_VERIFICATION_REQUEST',
      requestDetails: 'Requesting verification of the ownership papers currently on file for this parcel ahead of a registration transfer.',
      decisions: ['APPROVE'],
    },
    {
      ...ownedPick(5),
      workflowType: 'DOCUMENT_VERIFICATION_REQUEST',
      requestDetails: 'Requesting a fresh document verification - the existing record on file looks outdated.',
    },
    // Dispute filings - a citizen contesting something about a parcel they
    // hold, the one workflow type where "still pending" and "resolved either
    // way" all read as realistic outcomes.
    {
      ...ownedPick(6),
      workflowType: 'DISPUTE_FILING',
      requestDetails: 'Filing a boundary dispute - a neighbouring landholder has encroached on this parcel\'s northern boundary.',
      decisions: ['APPROVE'],
    },
    {
      ...ownedPick(7),
      workflowType: 'DISPUTE_FILING',
      requestDetails: 'Filing a dispute over an inheritance claim raised by a relative against this parcel.',
    },
  ];

  // Land claims: only valid on a parcel with no existing citizen link yet
  // (WorkflowsService.hasConflictingClaim), so these draw from the real
  // unclaimed-parcel pool computed above, not the owned-parcel picks.
  const claimCitizens = citizens.filter((c) => !citizensWithParcels.slice(0, 8).includes(c)).slice(0, 3);
  const claimTargets = unclaimedParcelIds.slice(0, claimCitizens.length);
  const claimDecisions: Array<Array<'APPROVE' | 'REJECT'> | undefined> = [['APPROVE'], ['REJECT'], undefined];
  claimCitizens.forEach((citizen, i) => {
    if (!claimTargets[i]) return;
    plans.push({
      citizen,
      parcelId: claimTargets[i],
      workflowType: 'LAND_CLAIM_REQUEST',
      requestDetails: 'I am the rightful owner of this parcel through ancestral inheritance and am not yet linked to it in the system; requesting registration of my claim.',
      decisions: claimDecisions[i],
    });
  });

  let created = 0;
  let decided = 0;
  for (const plan of plans) {
    const applicantContact = plan.citizen.mobileVerified ? plan.citizen.mobileNumber : plan.citizen.emailVerified ? plan.citizen.email : null;
    const result = await workflowsService.create({
      parcelId: plan.parcelId,
      workflowType: plan.workflowType,
      createdBy: plan.citizen.name,
      requestDetails: plan.requestDetails,
      citizenId: plan.citizen.id,
      applicantContact,
      applicantAddress: plan.citizen.address,
    });
    if (result === 'PARCEL_NOT_FOUND') {
      console.warn(`Skipped a ${plan.workflowType} for ${plan.citizen.email}: parcel ${plan.parcelId} not found`);
      continue;
    }
    created += 1;

    for (let i = 0; i < (plan.decisions?.length ?? 0); i++) {
      const step = result.steps[i];
      if (!step || step.status !== 'PENDING') break;
      const action = plan.decisions![i];
      const officer = officersByRole.get(OFFICER_ROLE_BY_DEPARTMENT[step.department]);
      if (!officer) break;

      const remarks =
        action === 'APPROVE'
          ? `${step.department.replace(/_/g, ' ')} review complete - documentation checked and in order. Approved.`
          : `${step.department.replace(/_/g, ' ')} review found an issue with this request that needs to be resolved before it can proceed. Rejected.`;

      const decided_ = await workflowsService.reviewStep(result.id, step.id, { action, remarks }, officer.role);
      if (typeof decided_ === 'string') {
        console.warn(`Could not advance step ${step.id} for workflow ${result.id}: ${decided_}`);
        break;
      }
      await auditService.log({
        userId: officer.id,
        userRole: officer.role,
        action: action === 'APPROVE' ? 'WORKFLOW_STEP_APPROVED' : 'WORKFLOW_STEP_REJECTED',
        entityType: 'WORKFLOW_STEP',
        entityId: step.id,
        parcelId: result.parcelId,
        metadata: { workflowId: result.id, department: step.department, remarks },
      });
      decided += 1;
      if (decided_.currentStatus === 'REJECTED') break;
    }
  }

  console.log(`Created ${created} demo service requests (${plans.length} planned) with ${decided} officer decisions applied across them.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
