import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'bn' | 'gu' | 'kn' | 'ml' | 'mr' | 'or' | 'pa' | 'ta' | 'te';

interface LanguageContextType {
  currentLang: SupportedLanguage;
  uiText: Record<string, string>;
  setLanguage: (lang: SupportedLanguage) => Promise<void>;
  t: (key: string, options?: Record<string, string | number> | string) => string;
  loading: boolean;
  translationFailed: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const SUPPORTED_LANGUAGES: SupportedLanguage[] = ['en', 'hi', 'bn', 'gu', 'kn', 'ml', 'mr', 'or', 'pa', 'ta', 'te'];
const STORAGE_KEY = 'bhoomisetu_lang';
const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1';

// Embedded fallback dictionary for instant responsiveness & offline resilience
export const FALLBACK_STRINGS: Record<string, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.features': 'Features',
    'nav.parcels': 'My Parcels',
    'nav.requests': 'Requests',
    'nav.profile': 'Profile',
    'nav.returnToPortal': 'Return to Portal',
    'citizenPortal.profileHeading': 'My Profile',
    'citizenPortal.profileRoleLabel': 'Role',
    'citizenPortal.profileRoleValue': 'Citizen',
    'citizenPortal.profileAccountTab': 'Account',
    'citizenPortal.profileDocumentsTab': 'Documents',
    'citizenPortal.profileNameLabel': 'Full Name',
    'citizenPortal.profileAddressLabel': 'Residential Address',
    'citizenPortal.profileGovernmentIdLabel': 'Government ID',
    'citizenPortal.profileOccupationLabel': 'Occupation',
    'citizenPortal.profileMemberSinceLabel': 'Member Since',
    'citizenPortal.profileLinkedParcelsLabel': 'Linked Parcels',
    'citizenPortal.profileTotalRequestsLabel': 'Total Requests',
    'citizenPortal.profileContactHeading': 'Identity & Contact Verification',
    'citizenPortal.profileContactDesc': 'Manage your phone and email contact details.',
    'citizenPortal.profileEmailLabel': 'Email address',
    'citizenPortal.profileMobileLabel': 'Mobile number',
    'citizenPortal.profileVerifiedBadge': 'Verified',
    'citizenPortal.profileUnverifiedBadge': 'Unverified',
    'citizenPortal.profileNotProvided': 'Not provided',
    'citizenPortal.profileAddCta': 'Add',
    'citizenPortal.profileChangeCta': 'Change',
    'citizenPortal.profileVerifyCta': 'Verify',
    'citizenPortal.profileEditCta': 'Edit',
    'citizenPortal.profileSaveCta': 'Save',
    'citizenPortal.profileCancelCta': 'Cancel',
    'citizenPortal.profileDetailsHeading': 'Profile Details',
    'citizenPortal.profileDetailsDesc': 'Your official registered profile details.',
    'citizenPortal.profilePendingNote': 'Verification pending for {{value}}',
    'citizenPortal.profileDocumentsEmpty': 'No documents are on file for this parcel yet.',
    'citizenPortal.profileDocumentsNoParcels': 'No parcels are linked to your account yet.',
    'placeholders.documentsTitle': 'Documents',
    'placeholders.documentsDesc': 'Land property papers on file for your linked parcels.',
    'auth.emailPlaceholder': 'Enter email address',
    'auth.mobilePlaceholder': '10-digit mobile number',
    'auth.otpVerifying': 'Verifying...',
    'citizenPortal.profileSendCodeCta': 'Send Code',
    'auth.otpSentTo': "We've sent a 6-digit code to {{target}}",
    'auth.otpCodeLabel': 'Verification Code',
    'auth.otpCodePlaceholder': '000000',
    'auth.otpVerifyButton': 'Verify',
    'auth.otpResendButton': 'Resend code',
    'auth.otpResendCooldown': 'Resend in {{seconds}}s',
    'auth.otpResendSuccess': 'A new code has been sent.',
    'auth.otpExpiresIn': 'Code expires in {{time}}',
    'auth.otpExpired': 'Code has expired. Please request a new one.',
    'auth.otpInvalid': 'Invalid or expired code. Please try again.',
    'auth.otpLockedOut': 'Too many incorrect attempts — request a new code.',
    'auth.otpSkipForNow': 'Skip for now — verify later from Profile',
    'citizenPortal.profileContactUpdateError': 'Failed to update contact. Please try again.',
'authPage.invalidCredentialsError': 'Invalid credentials.',
    'authPage.genericError': 'Something went wrong signing in. Please try again.',
    'authPage.gisLandGovernanceBadge': 'GIS Land Governance Platform',
    'authPage.loginHeroHeadline1': 'Welcome back to',
    'authPage.loginHeroHeadline2': 'BhoomiSetu',
    'authPage.loginHeroBody': 'Sign in to access your land records, requests, and cadastral maps.',
    'authPage.trustParcelsMapped': 'Parcels Mapped',
    'authPage.trustDeptFeeds': 'Department Feeds',
    'authPage.trustSvamitva': 'SVAMITVA Verified',
    'authPage.govtStripLogin': 'Government of India — Land Records',
    'authPage.signInHeading': 'Sign In',
    'authPage.signInSubtitle': 'Enter your credentials to access your account',
    'authPage.loginTabsAriaLabel': 'Login method',
    'authPage.emailTab': 'Email',
    'authPage.mobileTab': 'Login with Mobile',
    'authPage.emailAddressLabel': 'Email',
    'authPage.mobileNumberLabel': 'Mobile Number',
    'authPage.passwordLabel': 'Password',
    'authPage.hidePassword': 'Hide password',
    'authPage.showPassword': 'Show password',
    'authPage.signingIn': 'Signing in...',
    'authPage.signInCta': 'Sign in',
    'authPage.newCitizenPrompt': 'New to BhoomiSetu?',
    'authPage.createAccountLink': 'Create an account',
    'authPage.continueAsGuestLink': 'Continue as guest',
    'authPage.demoAccountsToggle': 'Demo accounts',
    'authPage.demoSharedPassword': 'Shared password for all demo accounts:',
    'authPage.demoAdminLabel': 'Admin',
    'authPage.demoOfficersLabel': 'Officers',
    'authPage.demoVerifiersLabel': 'Verifiers',
    'authPage.demoCitizenLabel': 'Citizens',
    'myParcels.newParcelButton': '+ New Parcel',
    'myParcels.blockedBannerTitle': 'Parcel Verification Required',
    'myParcels.blockedBannerDesc': 'You need to verify and link a parcel before raising a request. Click "+ New Parcel" to get started.',
    'myParcels.noParcelsHeading': 'No registered parcels on your profile',
    'myParcels.noParcelsDescription': 'You must link and verify a land parcel before you can view cadastral maps, request certificates, or raise complaints.',
    'myParcels.linkParcelCta': 'Link a Parcel to Get Started',
    'raiseRequestPage.linkParcelButton': 'Link a Parcel to Get Started',
    'raiseRequestPage.noParcelsHeading': 'No registered parcels on your profile',
    'raiseRequestPage.noParcelsDesc': 'A citizen can only raise complaints or requests against parcels linked and verified on their profile. Please link a parcel to unlock the request form.',
    'parcelVerification.heading': 'New Property Ownership Claim',
    'parcelVerification.subheading': 'Upload 7/12 or RoR document and verify parcel details',
    'parcelVerification.findMyParcelButton': 'Find My Parcel',
    'parcelVerification.verifyingButton': 'Running Verification Pipeline...',
    'map.loading': 'Loading parcels...',
    'map.errorLoading': 'Error loading parcels',
    'map.layersHeading': 'Layers',
    'map.layer.selected': 'Selected Parcel',
    'map.layer.adjacent': 'Adjacent Parcels',
    'map.layer.nearby': 'Nearby Parcels',
    'map.layer.cluster': 'Cluster Parcels',
    'map.layer.sameDistrict': 'Same District Parcels',
    'map.layer.zoning': 'Zoning Layer',
    'map.layer.restriction': 'Restriction Layer',
    'map.layer.infrastructure': 'Infrastructure Layer',
    'map.layer.changeDetection': 'Change Detection Layer',
    'map.basemap.street': 'Street',
    'map.basemap.satellite': 'Satellite',
    'map.basemap.terrain': 'Terrain',
    'map.popup.title': 'Parcel Details',
    'map.popup.id': 'ID',
    'map.popup.ulpin': 'ULPIN',
    'map.popup.notAvailable': 'N/A',
    'map.popup.state': 'State',
    'map.popup.district': 'District',
    'map.popup.area': 'Area',
    'unifiedMap.state': 'State',
    'unifiedMap.district': 'District',
    'unifiedMap.cluster': 'Cluster',
    'unifiedMap.year': 'Year',
    'unifiedMap.selectState': 'Select State',
    'unifiedMap.selectDistrict': 'Select District',
    'unifiedMap.selectCluster': 'Select Cluster',
    'unifiedMap.stateAria': 'Select State',
    'unifiedMap.districtAria': 'Select District',
    'unifiedMap.clusterAria': 'Select Cluster',
    'unifiedMap.yearAria': 'Select Year',
    'unifiedMap.locate': 'Locate',
    'unifiedMap.locateAria': 'Locate selected parcel on map',
    'unifiedMap.locateTooltip': 'Pan and zoom to the currently selected parcel',
    'unifiedMap.clusterLocked': 'Cluster Locked',
    'unifiedMap.loadingClusters': 'Loading clusters...',
    'landing.liveGisPreview.altText': 'Cadastral parcel map preview showing land boundaries and boundaries',
    'landing.liveGisPreview.parcelsCount': '{{count}} parcels mapped',
    'landing.liveGisPreview.liveDataBadge': 'Live Data',
    'schemes.section.eyebrow': 'Direct Farmer Benefits & Entitlements',
    'schemes.section.heading': 'Government Schemes Linked to Your Land',
    'schemes.section.subheading': 'Explore direct cash subsidies, low-interest agricultural loans, crop damage insurance, and clean solar power incentives verified through your land parcel.',
    'schemes.controls.play': 'Play',
    'schemes.controls.pause': 'Pause',
    'schemes.common.learnMore': 'Learn More',
    'schemes.common.forLabel': "Who it's for",
    'schemes.common.benefitLabel': 'Key Benefit',
    'schemes.common.officialPortal': 'Official Govt Scheme',
    'schemes.pmkisan.name': 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    'schemes.pmkisan.audience': 'Farmers with registered cultivable land',
    'schemes.pmkisan.benefit': '₹6,000/year direct bank transfer in 3 installments',
    'schemes.ulpin.name': 'ULPIN (Bhu-Aadhaar Digital Land ID)',
    'schemes.ulpin.audience': 'Owner of every land parcel',
    'schemes.ulpin.benefit': '14-digit digital land ID with map, GPS, ownership record — stops fraudulent claims',
    'schemes.kcc.name': 'Kisan Credit Card (KCC)',
    'schemes.kcc.audience': 'Land owners, lessees, sharecroppers',
    'schemes.kcc.benefit': 'Low-interest farm loan (~4% effective) based on land parcel size',
    'schemes.soilhealth.name': 'Soil Health Card',
    'schemes.soilhealth.audience': 'Any farmer with agricultural land',
    'schemes.soilhealth.benefit': 'Free soil testing + crop recommendation report',
    'schemes.pmfby.name': 'PMFBY (Pradhan Mantri Fasal Bima Yojana)',
    'schemes.pmfby.audience': 'Farmers growing crops on their land',
    'schemes.pmfby.benefit': 'Compensation if crop is damaged by drought/flood/hail/disease',
    'schemes.pmkusum.name': 'PM-KUSUM (Solar Agriculture Pump)',
    'schemes.pmkusum.audience': 'Farmers with irrigation land or barren land',
    'schemes.pmkusum.benefit': 'Up to 60% subsidy on solar pumps; sell surplus power from unused land',
    // officerPortal keys
    'officerPortal.approveCta': 'Approve',
    'officerPortal.rejectCta': 'Reject',
    'officerPortal.remarksRequiredLabel': 'Remarks (required)',
    'officerPortal.remarksPlaceholder': 'Enter your remarks for this decision',
    'officerPortal.remarksHelperText': 'Remarks are required to submit your decision.',
    'officerPortal.reviewSubmitError': 'Something went wrong submitting your decision. Please try again.',
    'officerPortal.alertSentTo': 'Alert sent to {{role}}.',
    'officerPortal.closeCta': 'Close',
    'officerPortal.escalateMessageLabel': 'Message to {{role}} (required)',
    'officerPortal.escalateMessagePlaceholder': 'Enter a message for the assigned officer',
    'officerPortal.escalateSubmitError': 'Failed to send alert. Please try again.',
    'officerPortal.sendAlertCta': 'Send Alert',
    'officerPortal.cancelCta': 'Cancel',
    'officerPortal.alertOfficerCta': 'Alert Officer',
    'officerPortal.decideMyselfCta': 'Decide Myself',
    'officerPortal.cancelJustMonitor': 'Cancel — just monitor',
    'officerPortal.reopenMessageLabel': 'Reason for sending this back to {{role}} (required)',
    'officerPortal.reopenMessagePlaceholder': 'Enter a reason for sending this back',
    'officerPortal.reopenSubmitError': 'Failed to send back for re-review. Please try again.',
    'officerPortal.sendBackCta': 'Send Back',
    'officerPortal.sendBackForReviewCta': 'Send Back for Re-Review',
    'officerPortal.assignVerifierLabel': 'Assign Verifier',
    'officerPortal.verificationNotTypicallyNeeded': 'Field verification is not typically needed for this workflow type.',
    'officerPortal.currentlyAssignedTo': 'Currently assigned to {{name}}',
    'officerPortal.noVerifiersAvailable': 'No verifiers available',
    'officerPortal.selectVerifierPlaceholder': 'Select a verifier',
    'officerPortal.fieldEvidenceLabel': 'Field Evidence',
    'officerPortal.fieldEvidenceAlt': 'Field evidence photo',
    'officerPortal.loadingWorkflow': 'Loading workflow...',
    'officerPortal.errorLoadingWorkflow': 'Error loading workflow',
    'officerPortal.applicantLabel': 'Applicant',
    'officerPortal.unknownLabel': 'Unknown',
    'officerPortal.landPropertyPapersLabel': 'Land Property Papers',
    'officerPortal.noDocumentOnFile': 'No document is on file for this parcel.',
    'officerPortal.submittedEvidenceLabel': 'Submitted Evidence',
    'officerPortal.attachedByApplicant': 'Attached by applicant',
    'officerPortal.submittedEvidenceAlt': 'Submitted evidence',
    'officerPortal.authenticitySuspiciousLabel': 'Authenticity check: suspicious',
    'officerPortal.automaticPrecheckLabel': 'OCR & Ownership Pre-Check',
    'officerPortal.viewParcelCta': 'View Parcel',
    'officerPortal.departmentRecordLabel': 'Department Record',
    'officerPortal.noDepartmentRecordOnFile': 'No department record on file for this parcel.',
    'officerPortal.reviewStepsLabel': 'Review Steps',
    'officerPortal.stepRemarksLabel': 'Remarks: {{text}}',
    'officerPortal.decidedLabel': 'Decided on {{date}}',
    'officerPortal.adminMonitoringHint': 'As admin, you are monitoring this workflow. Use "Alert Officer" to notify the assigned officer, or "Decide Myself" to make the decision yourself.',
    'officerPortal.adminReopenHint': 'All steps have been decided. Use "Send Back for Re-Review" to reopen a step.',
    'officerPortal.allStepsDecided': 'All steps have been decided.',
    'officerPortal.departmentAlreadyDecided': 'Your department has already decided this step.',
    'officerPortal.noStepForDepartment': 'No step in this workflow is assigned to your department.',
    'officerPortal.clusterLabel': 'Cluster',
    'officerPortal.alertRaisedBadge': 'Alert raised',
    'officerPortal.notEnoughHistoricalYears': 'Not enough historical years to compare',
    'officerPortal.comparingYearsLabel': 'Comparing {{fromYear}} to {{toYear}} - the only pair that can generate governance alerts.',
    'officerPortal.comparing': 'Comparing...',
    'officerPortal.compareYearsCta': 'Compare Years',
    'officerPortal.comparisonError': 'Could not run the comparison. Please try again.',
    'officerPortal.parcelsChangedStatus': '{{count}} parcels changed status between {{fromYear}} and {{toYear}}.',
    'officerPortal.noParcelsChangedStatus': "No parcel's status changed between {{fromYear}} and {{toYear}}.",
    'officerPortal.loadingClusters': 'Loading clusters...',
    'officerPortal.errorLoadingClusters': 'Error loading clusters',
    'officerPortal.noHistoricalImagery': 'No historical imagery has been generated yet.',
    // common keys
    'common.notApplicable': 'N/A',
    'common.yes': 'Yes',
    'common.no': 'No',
    // parcel360 keys
    'parcel360.field.sourceSchema': 'Source Schema',
    'parcel360.field.sourceIdentifier': 'Source Identifier',
    'parcel360.field.ownerName': 'Owner Name',
    'parcel360.area': 'Area',
    'parcel360.field.locality': 'Locality',
    'verificationCard.status': 'Status',
    'parcel360.field.registrationNumber': 'Registration Number',
    'parcel360.field.registrationDate': 'Registration Date',
    'parcel360.field.lastTransaction': 'Last Transaction',
    'parcel360.field.lastTransactionDate': 'Last Transaction Date',
    'parcel360.field.landUse': 'Land Use',
    'parcel360.field.zoningClassification': 'Zoning Classification',
    'parcel360.field.masterPlanReference': 'Master Plan Reference',
    'parcel360.field.buildingPermission': 'Building Permission',
    'parcel360.field.assessedValue': 'Assessed Value',
    'parcel360.field.annualTax': 'Annual Tax',
    'parcel360.field.taxStatus': 'Tax Status',
    'parcel360.field.outstandingAmount': 'Outstanding Amount',
    'parcel360.field.lastPaymentDate': 'Last Payment Date',
    'parcel360.field.hasRestriction': 'Has Restriction',
    'parcel360.field.restrictionType': 'Restriction Type',
    'parcel360.field.details': 'Details',
    'parcel360.field.imposingAuthority': 'Imposing Authority',
    'parcel360.field.hasActiveDispute': 'Has Active Dispute',
    'parcel360.field.disputeType': 'Dispute Type',
    'parcel360.field.caseStatus': 'Case Status',
    'parcel360.field.filingDate': 'Filing Date',
    'parcel360.field.hasEncumbrance': 'Has Encumbrance',
    'parcel360.field.encumbranceType': 'Encumbrance Type',
    'parcel360.field.lenderName': 'Lender Name',
    'parcel360.field.instrumentReference': 'Instrument Reference',
  },
  hi: {
    'nav.home': 'होम',
    'nav.about': 'परिचय',
    'nav.features': 'सुविधाएं',
    'nav.parcels': 'मेरे भूखंड',
    'nav.requests': 'अनुरोध',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.returnToPortal': 'पोर्टल पर लौटें',
    'citizenPortal.profileHeading': 'मेरी प्रोफ़ाइल',
    'citizenPortal.profileRoleLabel': 'भूमिका',
    'citizenPortal.profileRoleValue': 'नागरिक',
    'citizenPortal.profileAccountTab': 'खाता',
    'citizenPortal.profileDocumentsTab': 'दस्तावेज़',
    'citizenPortal.profileNameLabel': 'पूरा नाम',
    'citizenPortal.profileAddressLabel': 'आवासीय पता',
    'citizenPortal.profileGovernmentIdLabel': 'सरकारी पहचान पत्र',
    'citizenPortal.profileOccupationLabel': 'व्यवसाय',
    'citizenPortal.profileMemberSinceLabel': 'सदस्यता तिथि',
    'citizenPortal.profileLinkedParcelsLabel': 'लिंक किए गए भूखंड',
    'citizenPortal.profileTotalRequestsLabel': 'कुल अनुरोध',
    'citizenPortal.profileContactHeading': 'पहचान एवं संपर्क सत्यापन',
    'citizenPortal.profileContactDesc': 'अपना फ़ोन और ईमेल संपर्क प्रबंधित करें।',
    'citizenPortal.profileEmailLabel': 'ईमेल पता',
    'citizenPortal.profileMobileLabel': 'मोबाइल नंबर',
    'citizenPortal.profileVerifiedBadge': 'सत्यापित (Verified)',
    'citizenPortal.profileUnverifiedBadge': 'असत्यापित (Unverified)',
    'citizenPortal.profileNotProvided': 'उपलब्ध नहीं',
    'citizenPortal.profileAddCta': 'जोड़ें',
    'citizenPortal.profileChangeCta': 'बदलें',
    'citizenPortal.profileVerifyCta': 'सत्यापित करें',
    'citizenPortal.profileEditCta': 'संपादित करें',
    'citizenPortal.profileSaveCta': 'सहेजें',
    'citizenPortal.profileCancelCta': 'रद्द करें',
    'citizenPortal.profileDetailsHeading': 'प्रोफ़ाइल विवरण',
    'citizenPortal.profileDetailsDesc': 'आपका पंजीकृत आधिकारिक प्रोफ़ाइल विवरण।',
    'citizenPortal.profilePendingNote': '{{value}} के लिए सत्यापन लंबित है',
    'citizenPortal.profileDocumentsEmpty': 'इस भूखंड के लिए कोई दस्तावेज़ नहीं मिला।',
    'citizenPortal.profileDocumentsNoParcels': 'दस्तावेज़ प्रदर्शित करने के लिए कोई भूखंड लिंक नहीं है।',
    'placeholders.documentsTitle': 'दस्तावेज़',
    'placeholders.documentsDesc': 'आपके लिंक किए गए भूखंडों के लिए भूमि दस्तावेज।',
    'myParcels.newParcelButton': '+ नया भूखंड',
    'myParcels.blockedBannerTitle': 'भूखंड सत्यापन आवश्यक',
    'myParcels.blockedBannerDesc': 'अनुरोध दर्ज करने से पहले आपको एक भूखंड सत्यापित और लिंक करना होगा। शुरू करने के लिए "+ नया भूखंड" पर क्लिक करें।',
    'myParcels.noParcelsHeading': 'आपकी प्रोफ़ाइल पर कोई पंजीकृत भूखंड नहीं है',
    'myParcels.linkParcelCta': 'यहाँ दबाएं भूखंड लिंक करने के लिए',
    'raiseRequestPage.linkParcelButton': 'यहाँ दबाएं भूखंड लिंक करने के लिए',
    'raiseRequestPage.noParcelsHeading': 'आपकी प्रोफ़ाइल पर कोई पंजीकृत भूखंड नहीं है',
    'raiseRequestPage.noParcelsDesc': 'नागरिक केवल अपनी प्रोफ़ाइल पर सत्यापित और जुड़े हुए भूखंडों के विरुद्ध ही शिकायत या अनुरोध दर्ज कर सकते हैं।',
    'parcelVerification.heading': 'नया संपत्ति स्वामित्व दावा',
    'parcelVerification.subheading': '७/१२ या RoR दस्तावेज़ अपलोड करें और स्वामित्व सत्यापित करें',
    'parcelVerification.findMyParcelButton': 'मेरा भूखंड खोजें',
    'parcelVerification.verifyingButton': 'सत्यापन पाइपलाइन चल रही है...',
    'schemes.section.eyebrow': 'प्रत्यक्ष किसान लाभ एवं अधिकार',
    'schemes.section.heading': 'आपकी भूमि से जुड़ी सरकारी योजनाएं',
    'schemes.section.subheading': 'अपने भूखंड से सत्यापित प्रत्यक्ष नकद सब्सिडी, कम ब्याज वाले कृषि ऋण, फसल सुरक्षा और सौर ऊर्जा प्रोत्साहन देखें।',
    'schemes.controls.play': 'चलाएं',
    'schemes.controls.pause': 'रोकें',
    'schemes.common.learnMore': 'अधिक जानें',
    'schemes.common.forLabel': 'पात्रता',
    'schemes.common.benefitLabel': 'मुख्य लाभ',
    'schemes.common.officialPortal': 'आधिकारिक सरकारी योजना',
    'schemes.pmkisan.name': 'PM-KISAN (प्रधानमंत्री किसान सम्मान निधि)',
    'schemes.pmkisan.audience': 'पंजीकृत कृषि योग्य भूमि वाले किसान',
    'schemes.pmkisan.benefit': '3 किस्तों में प्रति वर्ष ₹6,000 प्रत्यक्ष बैंक हस्तांतरण',
    'schemes.ulpin.name': 'ULPIN (भू-आधार डिजिटल लैंड आईडी)',
    'schemes.ulpin.audience': 'प्रत्येक भूखंड के पंजीकृत स्वामी',
    'schemes.ulpin.benefit': 'मानचित्र, जीपीएस और स्वामित्व रिकॉर्ड युक्त 14-अंकीय डिजिटल आईडी — धोखाधड़ी पर रोक',
    'schemes.kcc.name': 'Kisan Credit Card (KCC ऋण)',
    'schemes.kcc.audience': 'भूमि स्वामी, पट्टेदार और बटाईदार किसान',
    'schemes.kcc.benefit': 'भूखंड के आकार पर आधारित कम ब्याज वाला कृषि ऋण (~4% प्रभावी)',
    'schemes.soilhealth.name': 'Soil Health Card (मृदा स्वास्थ्य कार्ड)',
    'schemes.soilhealth.audience': 'कृषि भूमि वाला कोई भी किसान',
    'schemes.soilhealth.benefit': 'निःशुल्क मिट्टी परीक्षण + फसल पोषण अनुशंसा रिपोर्ट',
    'schemes.pmfby.name': 'PMFBY (प्रधानमंत्री फसल बीमा योजना)',
    'schemes.pmfby.audience': 'अपनी भूमि पर फसल उगाने वाले किसान',
    'schemes.pmfby.benefit': 'सूखा, बाढ़, ओलावृष्टि या रोग से फसल क्षति पर वित्तीय मुआवजा',
    'schemes.pmkusum.name': 'PM-KUSUM (सौर कृषि पंप योजना)',
    'schemes.pmkusum.audience': 'सिंचाई भूमि या बंजर भूमि वाले किसान',
    'schemes.pmkusum.benefit': 'सौर पंपों पर 60% तक सब्सिडी; अप्रयुक्त भूमि से अतिरिक्त बिजली बेचें',
    'map.basemap.street': 'सड़क',
    'map.basemap.satellite': 'उपग्रह',
    'map.basemap.terrain': 'भूभाग',
    'map.popup.title': 'भूखंड विवरण',
    'map.popup.id': 'आईडी',
    'map.popup.ulpin': 'ULPIN',
    'map.popup.notAvailable': 'उपलब्ध नहीं',
    'map.popup.state': 'राज्य',
    'map.popup.district': 'जिला',
    'map.popup.area': 'क्षेत्र',
    'unifiedMap.state': 'राज्य',
    'unifiedMap.district': 'जिला',
    'unifiedMap.cluster': 'समूह',
    'unifiedMap.year': 'वर्ष',
    'unifiedMap.selectState': 'राज्य चुनें',
    'unifiedMap.selectDistrict': 'जिला चुनें',
    'unifiedMap.selectCluster': 'समूह चुनें',
    'unifiedMap.stateAria': 'राज्य चुनें',
    'unifiedMap.districtAria': 'जिला चुनें',
    'unifiedMap.clusterAria': 'समूह चुनें',
    'unifiedMap.yearAria': 'वर्ष चुनें',
    'unifiedMap.locate': 'पता लगाएं',
    'unifiedMap.locateAria': 'मानचित्र पर चयनित भूखंड का पता लगाएं',
    'unifiedMap.locateTooltip': 'वर्तमान में चयनित भूखंड पर पैन और ज़ूम करें',
    'unifiedMap.clusterLocked': 'समूह लॉक',
    'unifiedMap.loadingClusters': 'समूह लोड हो रहे हैं...',
    'landing.liveGisPreview.altText': 'भू-सीमाओं और सीमाओं को दिखाने वाले कैडस्ट्राल भूखंड मानचित्र का पूर्वावलोकन',
    'landing.liveGisPreview.parcelsCount': '{{count}} भूखंड मानचित्रित',
    'landing.liveGisPreview.liveDataBadge': 'लाइव डेटा',
  },
  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.about': 'माहिती',
    'nav.features': 'वैशिष्ट्ये',
    'nav.parcels': 'माझे भूखंड',
    'nav.requests': 'विनंत्या',
    'nav.profile': 'माझे प्रोफाईल',
    'nav.returnToPortal': 'पोर्टलवर परत जा',
    'citizenPortal.profileHeading': 'माझे प्रोफाईल',
    'citizenPortal.profileRoleLabel': 'भूमिका',
    'citizenPortal.profileRoleValue': 'नागरिक',
    'citizenPortal.profileAccountTab': 'खाते',
    'citizenPortal.profileDocumentsTab': 'दस्तऐवज',
    'citizenPortal.profileNameLabel': 'पूर्ण नाव',
    'citizenPortal.profileAddressLabel': 'निवासी पत्ता',
    'citizenPortal.profileGovernmentIdLabel': 'सरकारी ओळखपत्र',
    'citizenPortal.profileOccupationLabel': 'व्यवसाय',
    'citizenPortal.profileMemberSinceLabel': 'नोंदणी तारीख',
    'citizenPortal.profileLinkedParcelsLabel': 'संलग्न भूखंड',
    'citizenPortal.profileTotalRequestsLabel': 'एकूण विनंत्या',
    'citizenPortal.profileContactHeading': 'ओळख व संपर्क पडताळणी',
    'citizenPortal.profileContactDesc': 'तुमचा फोन आणि ईमेल संपर्क व्यवस्थापित करा.',
    'citizenPortal.profileEmailLabel': 'ईमेल पत्ता',
    'citizenPortal.profileMobileLabel': 'मोबाईल नंबर',
    'citizenPortal.profileVerifiedBadge': 'पडताळणीकृत (Verified)',
    'citizenPortal.profileUnverifiedBadge': 'अपडताळणीकृत (Unverified)',
    'citizenPortal.profileNotProvided': 'दिलेले नाही',
    'citizenPortal.profileAddCta': 'जोडा',
    'citizenPortal.profileChangeCta': 'बदला',
    'citizenPortal.profileVerifyCta': 'पडताळा',
    'citizenPortal.profileEditCta': 'संपादित करा',
    'citizenPortal.profileSaveCta': 'जतन करा',
    'citizenPortal.profileCancelCta': 'रद्द करा',
    'citizenPortal.profileDetailsHeading': 'प्रोफाईल तपशील',
    'citizenPortal.profileDetailsDesc': 'तुमचा अधिकृत नोंदणीकृत प्रोफाईल तपशील.',
    'citizenPortal.profilePendingNote': '{{value}} साठी पडताळणी प्रलंबित आहे',
    'citizenPortal.profileDocumentsEmpty': 'या भूखंडासाठी कोणतेही दस्तऐवज आढळले नाहीत.',
    'citizenPortal.profileDocumentsNoParcels': 'दस्तऐवज दाखवण्यासाठी कोणतेही भूखंड संलग्न नाहीत.',
    'placeholders.documentsTitle': 'दस्तऐवज',
    'placeholders.documentsDesc': 'तुमच्या संलग्न भूखंडांचे जमिनीचे कागदपत्रे.',
    'myParcels.newParcelButton': '+ नवीन भूखंड',
    'myParcels.blockedBannerTitle': 'भूखंड पडताळणी आवश्यक',
    'myParcels.blockedBannerDesc': 'तक्रार किंवा विनंती दाखल करण्यापूर्वी तुम्हाला भूखंड पडताळून संलग्न करणे आवश्यक आहे. सुरू करण्यासाठी "+ नवीन भूखंड" वर क्लिक करा.',
    'myParcels.noParcelsHeading': 'तुमच्या प्रोफाईलवर कोणतेही नोंदणीकृत भूखंड नाहीत',
    'myParcels.linkParcelCta': 'येथे क्लिक करा भूखंड लिंक करण्यासाठी',
    'raiseRequestPage.linkParcelButton': 'येथे क्लिक करा भूखंड लिंक करण्यासाठी',
    'raiseRequestPage.noParcelsHeading': 'तुमच्या प्रोफाईलवर कोणतेही नोंदणीकृत भूखंड नाहीत',
    'raiseRequestPage.noParcelsDesc': 'नागरिक फक्त त्यांच्या प्रोफाईलवर पडताळणी केलेल्या आणि जोडलेल्या भूखंडांवरच तक्रार किंवा विनंती दाखल करू शकतात.',
    'parcelVerification.heading': 'नवीन मालमत्ता मालकी हक्क दावा',
    'parcelVerification.subheading': '७/१२ किंवा RoR दस्तऐवज अपलोड करा आणि भूखंड पडताळा',
    'parcelVerification.findMyParcelButton': 'माझा भूखंड शोधा',
    'parcelVerification.verifyingButton': 'पडताळणी प्रक्रिया सुरू आहे...',
    'schemes.section.eyebrow': 'थेट शेतकरी लाभ व शासकीय योजना',
    'schemes.section.heading': 'तुमच्या जमिनीशी संलग्न शासकीय योजना',
    'schemes.section.subheading': 'तुमच्या भूखंडाशी जोडलेली थेट आर्थिक मदत, कमी व्याजाचे पीक कर्ज, पीक विमा आणि सौर ऊर्जा योजनांची माहिती मिळवा.',
    'schemes.controls.play': 'सुरू करा',
    'schemes.controls.pause': 'थांबवा',
    'schemes.common.learnMore': 'अधिक माहिती',
    'schemes.common.forLabel': 'पात्रता',
    'schemes.common.benefitLabel': 'मुख्य लाभ',
    'schemes.common.officialPortal': 'अधिकृत शासकीय योजना',
    'schemes.pmkisan.name': 'PM-KISAN (प्रधानमंत्री किसान सन्मान निधी)',
    'schemes.pmkisan.audience': 'नोंदणीकृत लागवडीयोग्य जमीन असलेले शेतकरी',
    'schemes.pmkisan.benefit': '3 हप्त्यांमध्ये दरवर्षी ₹6,000 थेट बँक खात्यात',
    'schemes.ulpin.name': 'ULPIN (भू-आधार डिजिटल जमीन ओळख)',
    'schemes.ulpin.audience': 'प्रत्येक भूखंडाचे अधिकृत मालक',
    'schemes.ulpin.benefit': 'नकाशा, जीपीएस आणि मालकी नोंदीसह 14-अंकी डिजिटल आयडी — फसवणूक रोखण्यास मदत',
    'schemes.kcc.name': 'Kisan Credit Card (KCC कर्ज)',
    'schemes.kcc.audience': 'जमीन मालक, भाडेकरू व शेतकरी',
    'schemes.kcc.benefit': 'जमिनीच्या क्षेत्रफळानुसार कमी व्याजाचे (~4% प्रभावी) कृषी कर्ज',
    'schemes.soilhealth.name': 'Soil Health Card (मृदा आरोग्य पत्रिका)',
    'schemes.soilhealth.audience': 'शेतीयोग्य जमीन असलेले सर्व शेतकरी',
    'schemes.soilhealth.benefit': 'मोफत माती परीक्षण + योग्य खत व पीक शिफारस अहवाल',
    'schemes.pmfby.name': 'PMFBY (प्रधानमंत्री पीक विमा योजना)',
    'schemes.pmfby.audience': 'आपल्या जमिनीवर पीक घेणारे शेतकरी',
    'schemes.pmfby.benefit': 'दुष्काळ, पूर, गारपीट किंवा रोगामुळे पीक नुकसान झाल्यास आर्थिक भरपाई',
    'schemes.pmkusum.name': 'PM-KUSUM (सौर कृषी पंप योजना)',
    'schemes.pmkusum.audience': 'बागायती किंवा पडीक जमीन असलेले शेतकरी',
    'schemes.pmkusum.benefit': 'सौर पंपावर 60% पर्यंत अनुदान; पडीक जमिनीतून अतिरिक्त वीज विक्रीची संधी',
  },
  gu: {
    'nav.home': 'હોમ',
    'nav.about': 'પરિચય',
    'nav.features': 'સુવિધાઓ',
    'nav.parcels': 'મારા પાર્સલ',
    'nav.requests': 'વિનંતીઓ',
    'nav.profile': 'મારી પ્રોફાઇલ',
    'nav.returnToPortal': 'પોર્ટલ પર પાછા જાઓ',
    'schemes.section.eyebrow': 'પ્રત્યક્ષ ખેડૂત લાભો અને અધિકારો',
    'schemes.section.heading': 'તમારી જમીન સાથે જોડાયેલ સરકારી યોજનાઓ',
    'schemes.section.subheading': 'તમારા જમીન પાર્સલ દ્વારા ચકાસાયેલ પ્રત્યક્ષ સબસિડી, ઓછા વ્યાજની કૃષિ લોન, પાક વીમો અને સૌર ઉર્જા યોજનાઓ મેળવો.',
    'schemes.controls.play': 'ચાલુ કરો',
    'schemes.controls.pause': 'થોભાવો',
    'schemes.common.learnMore': 'વધુ જાણો',
    'schemes.common.forLabel': 'કોના માટે છે',
    'schemes.common.benefitLabel': 'મુખ્ય લાભ',
    'schemes.common.officialPortal': 'સત્તાવાર સરકારી યોજના',
    'schemes.pmkisan.name': 'PM-KISAN (પ્રધાનમંત્રી કિસાન સન્માન નિધિ)',
    'schemes.pmkisan.audience': 'નોંધાયેલ ખેતીલાયક જમીન ધરાવતા ખેડૂતો',
    'schemes.pmkisan.benefit': '3 હપ્તામાં વાર્ષિક ₹6,000 સીધા બેંક ખાતામાં ટ્રાન્સફર',
    'schemes.ulpin.name': 'ULPIN (ભૂ-આધાર ડિજિટલ લેન્ડ આઈડી)',
    'schemes.ulpin.audience': 'દરેક જમીન પાર્સલના માલિક',
    'schemes.ulpin.benefit': 'નકશો, જીપીએસ અને માલિકીના રેકોર્ડ સાથે 14-અંકનું ડિજિટલ આઈડી — છેતરપિંડી અટકાવે છે',
    'schemes.kcc.name': 'Kisan Credit Card (KCC લોન)',
    'schemes.kcc.audience': 'જમીન માલિકો, પટ્ટાધારકો અને ભાગીદારો',
    'schemes.kcc.benefit': 'જમીનના કદ મુજબ ઓછું વ્યાજ (~4% અસરકારક) ધરાવતી કૃષિ લોન',
    'schemes.soilhealth.name': 'Soil Health Card (જમીન આરોગ્ય કાર્ડ)',
    'schemes.soilhealth.audience': 'ખેતીની જમીન ધરાવતો કોઈપણ ખેડૂત',
    'schemes.soilhealth.benefit': 'મફત જમીન પરીક્ષણ + પાક ભલામણ અહેવાલ',
    'schemes.pmfby.name': 'PMFBY (પ્રધાનમંત્રી ફસલ બીમા યોજના)',
    'schemes.pmfby.audience': 'પોતાની જમીન પર પાક ઉગાડતા ખેડૂતો',
    'schemes.pmfby.benefit': 'દુષ્કાળ, પૂર, કરા કે રોગથી પાકને નુકસાન થાય તો વળતર',
    'schemes.pmkusum.name': 'PM-KUSUM (સોલર કૃષિ પંપ યોજના)',
    'schemes.pmkusum.audience': 'પિયત જમીન અથવા બિનઉપયોગી જમીન ધરાવતા ખેડૂતો',
    'schemes.pmkusum.benefit': 'સોલર પંપ પર 60% સુધી સબસિડી; બિનઉપયોગી જમીન પરથી વધારાની વીજળી વેચો',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.about': 'সম্পর্কে',
    'nav.features': 'বৈশিষ্ট্য',
    'nav.parcels': 'আমার জমি',
    'nav.requests': 'অনুরোধ',
    'nav.profile': 'আমার প্রোফাইল',
    'nav.returnToPortal': 'পোর্টালে ফিরে যান',
    'schemes.section.eyebrow': 'প্রত্যক্ষ কৃষক সুবিধা ও সরকারি অধিকার',
    'schemes.section.heading': 'আপনার জমির সাথে সংযুক্ত সরকারি প্রকল্প',
    'schemes.section.subheading': 'আপনার জমির তথ্যের মাধ্যমে যাচাইকৃত সরাসরি নগদ ভর্তুকি, স্বল্প সুদের কৃষি ঋণ, ফসল ক্ষতিপূরণ এবং সৌর বিদ্যুৎ সুবিধা পান।',
    'schemes.controls.play': 'চালান',
    'schemes.controls.pause': 'থামান',
    'schemes.common.learnMore': 'আরও জানুন',
    'schemes.common.forLabel': 'কার জন্য',
    'schemes.common.benefitLabel': 'প্রধান সুবিধা',
    'schemes.common.officialPortal': 'অফিসিয়াল সরকারি প্রকল্প',
    'schemes.pmkisan.name': 'PM-KISAN (প্রধানমন্ত্রী কিষাণ সম্মান নিধি)',
    'schemes.pmkisan.audience': 'নিবন্ধিত আবাদযোগ্য জমির অধিকারী কৃষক',
    'schemes.pmkisan.benefit': '৩টি কিস্তিতে প্রতি বছর ₹6,000 সরাসরি ব্যাঙ্ক ট্রান্সফার',
    'schemes.ulpin.name': 'ULPIN (ভূ-আধার ডিজিটাল ল্যান্ড আইডি)',
    'schemes.ulpin.audience': 'প্রতিটি জমির প্লটের মালিক',
    'schemes.ulpin.benefit': 'ম্যাপ, জিপিএস ও মালিকানা রেকর্ডসহ ১৪-সংখ্যার ডিজিটাল আইডি — প্রতারণা রোধ করে',
    'schemes.kcc.name': 'Kisan Credit Card (KCC ঋণ)',
    'schemes.kcc.audience': 'জমি মালিক, ইজারাদার ও ভাগচাষী কৃষক',
    'schemes.kcc.benefit': 'জমির পরিমাণের ভিত্তিতে স্বল্প সুদের (~4% কার্যকর) কৃষি ঋণ',
    'schemes.soilhealth.name': 'Soil Health Card (মৃত্তিকা স্বাস্থ্য কার্ড)',
    'schemes.soilhealth.audience': 'কৃষি জমি থাকা যে কোনো কৃষক',
    'schemes.soilhealth.benefit': 'বিনামূল্যে মাটি পরীক্ষা + ফসল পুষ্টি সুপারিশ রিপোর্ট',
    'schemes.pmfby.name': 'PMFBY (প্রধানমন্ত্রী ফসল বীমা যোজনা)',
    'schemes.pmfby.audience': 'নিজের জমিতে ফসল ফলানো কৃষক',
    'schemes.pmfby.benefit': 'খরা, বন্যা, শিলাবৃষ্টি বা রোগে ফসল নষ্ট হলে ক্ষতিপূরণ',
    'schemes.pmkusum.name': 'PM-KUSUM (সৌর কৃষি পাম্প প্রকল্প)',
    'schemes.pmkusum.audience': 'সেচ বা অনাবাদী জমি থাকা কৃষক',
    'schemes.pmkusum.benefit': 'সোলার পাম্পে ৬০% পর্যন্ত ভর্তুকি; অব্যবহৃত জমি থেকে অতিরিক্ত বিদ্যুৎ বিক্রি করুন',
  },
  kn: {
    'nav.home': 'ಮುಖಪುಟ',
    'nav.about': 'ಕುರಿತು',
    'nav.features': 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    'nav.parcels': 'ನನ್ನ ಜಮೀನುಗಳು',
    'nav.requests': 'ವಿನಂತಿಗಳು',
    'nav.profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'nav.returnToPortal': 'ಪೋರ್ಟಲ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    'schemes.section.eyebrow': 'ರೈತರ ನೇರ ಸೌಲಭ್ಯಗಳು ಮತ್ತು ಹಕ್ಕುಗಳು',
    'schemes.section.heading': 'ನಿಮ್ಮ ಭೂಮಿಗೆ ಸಂಬಂಧಿಸಿದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    'schemes.section.subheading': 'ನಿಮ್ಮ ಜಮೀನಿನ ಮೂಲಕ ಪರಿಶೀಲಿಸಲಾದ ನೇರ ನಗದು ಸಬ್ಸಿಡಿ, ಕಡಿಮೆ ಬಡ್ಡಿಯ ಕೃಷಿ ಸಾಲ, ಬೆಳೆ ವಿಮೆ ಮತ್ತು ಸೌರ ವಿದ್ಯುತ್ ಯೋಜನೆಗಳ ಮಾಹಿತಿ ಪಡೆಯಿರಿ.',
    'schemes.controls.play': 'ಪ್ಲೇ ಮಾಡಿ',
    'schemes.controls.pause': 'ವಿರಾಮಗೊಳಿಸಿ',
    'schemes.common.learnMore': 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
    'schemes.common.forLabel': 'ಯಾರಿಗೆ ಅನ್ವಯ',
    'schemes.common.benefitLabel': 'ಮುಖ್ಯ ಪ್ರಯೋಜನ',
    'schemes.common.officialPortal': 'ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಯೋಜನೆ',
    'schemes.pmkisan.name': 'PM-KISAN (ಪ್ರಧಾನ ಮಂತ್ರಿ ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ)',
    'schemes.pmkisan.audience': 'ನೋಂದಾಯಿತ ಸಾಗುವಳಿ ಭೂಮಿ ಹೊಂದಿರುವ ರೈತರು',
    'schemes.pmkisan.benefit': '3 ಕಂತುಗಳಲ್ಲಿ ವರ್ಷಕ್ಕೆ ₹6,000 ನೇರ ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ',
    'schemes.ulpin.name': 'ULPIN (ಭೂ-ಆಧಾರ್ ಡಿಜಿಟಲ್ ಲ್ಯಾಂಡ್ ಐಡಿ)',
    'schemes.ulpin.audience': 'ಪ್ರತಿಯೊಂದು ಭೂ ಹಿಡುವಳಿಯ ಮಾಲೀಕರು',
    'schemes.ulpin.benefit': 'ನಕ್ಷೆ, ಜಿಪಿಎಸ್ ಮತ್ತು ಮಾಲೀಕತ್ವದ ದಾಖಲೆಯೊಂದಿಗೆ 14-ಅಂಕಿಯ ಡಿಜಿಟಲ್ ಐಡಿ — ವಂಚನೆ ತಡೆಯುತ್ತದೆ',
    'schemes.kcc.name': 'Kisan Credit Card (KCC ಸಾಲ)',
    'schemes.kcc.audience': 'ಭೂ ಮಾಲೀಕರು, ಗೇಣಿದಾರರು ಮತ್ತು ಪಾಲುದಾರ ರೈತರು',
    'schemes.kcc.benefit': 'ಜಮೀನಿನ ವಿಸ್ತೀರ್ಣದ ಆಧಾರದ ಮೇಲೆ ಕಡಿಮೆ ಬಡ್ಡಿಯ (~4% ಪರಿಣಾಮಕಾರಿ) ಕೃಷಿ ಸಾಲ',
    'schemes.soilhealth.name': 'Soil Health Card (ಮಣ್ಣು ಆರೋಗ್ಯ ಕಾರ್ಡ್)',
    'schemes.soilhealth.audience': 'ಕೃಷಿ ಭೂಮಿ ಹೊಂದಿರುವ ಯಾವುದೇ ರೈತ',
    'schemes.soilhealth.benefit': 'ಉಚಿತ ಮಣ್ಣು ಪರೀಕ್ಷೆ + ಬೆಳೆ ಪೋಷಕಾಂಶ ಶಿಫಾರಸು ವರದಿ',
    'schemes.pmfby.name': 'PMFBY (ಪ್ರಧಾನ ಮಂತ್ರಿ ಫಸಲ್ ಬಿಮಾ ಯೋಜನೆ)',
    'schemes.pmfby.audience': 'ತಮ್ಮ ಜಮೀನಿನಲ್ಲಿ ಬೆಳೆ ಬೆಳೆಯುವ ರೈತರು',
    'schemes.pmfby.benefit': 'ಬರ, ಪ್ರವಾಹ, ಆಲಿಕಲ್ಲು ಮಳೆ ಅಥವಾ ರೋಗಗಳಿಂದ ಬೆಳೆ ನಷ್ಟವಾದರೆ ಪರಿಹಾರ',
    'schemes.pmkusum.name': 'PM-KUSUM (ಸೌರ ಕೃಷಿ ಪಂಪ್ ಯೋಜನೆ)',
    'schemes.pmkusum.audience': 'ನೀರಾವರಿ ಅಥವಾ ಪಾಳು ಭೂಮಿ ಹೊಂದಿರುವ ರೈತರು',
    'schemes.pmkusum.benefit': 'ಸೌರ ಪಂಪ್‌ಗಳಿಗೆ 60% ವರೆಗೆ ಸಬ್ಸಿಡಿ; ಬಳಕೆಯಾಗದ ಭೂಮಿಯಿಂದ ಹೆಚ್ಚುವರಿ ವಿದ್ಯುತ್ ಮಾರಾಟ',
  },
  ml: {
    'nav.home': 'ഹോം',
    'nav.about': 'വിവരണം',
    'nav.features': 'സവിശേഷതകൾ',
    'nav.parcels': 'എന്റെ ഭൂമി',
    'nav.requests': 'അപേക്ഷകൾ',
    'nav.profile': 'പ്രൊഫൈൽ',
    'nav.returnToPortal': 'പോർട്ടലിലേക്ക് മടങ്ങുക',
    'schemes.section.eyebrow': 'നേരിട്ടുള്ള കർഷക ആനുകൂല്യങ്ങളും അവകാശങ്ങളും',
    'schemes.section.heading': 'നിങ്ങളുടെ ഭൂമിയുമായി ബന്ധിപ്പിച്ച സർക്കാർ പദ്ധതികൾ',
    'schemes.section.subheading': 'നിങ്ങളുടെ ഭൂമി അടിസ്ഥാനമാക്കി നേരിട്ടുള്ള ധനസഹായം, കുറഞ്ഞ പലിശ നിരക്കിലുള്ള കാർഷിക വായ്പ, വിള ഇൻഷുറൻസ്, സൗരോർജ്ജ പദ്ധതികൾ എന്നിവ കണ്ടെത്തൂ.',
    'schemes.controls.play': 'പ്ലേ ചെയ്യുക',
    'schemes.controls.pause': 'താൽക്കാലികമായി നിർത്തുക',
    'schemes.common.learnMore': 'കൂടുതൽ അറിയുക',
    'schemes.common.forLabel': 'ആർക്കാണ് അർഹത',
    'schemes.common.benefitLabel': 'പ്രധാന നേട്ടം',
    'schemes.common.officialPortal': 'ഔദ്യോഗിക സർക്കാർ പദ്ധതി',
    'schemes.pmkisan.name': 'PM-KISAN (പ്രധാനമന്ത്രി കിസാൻ സമ്മാൻ നിധി)',
    'schemes.pmkisan.audience': 'കൃഷിഭൂമി സ്വന്തമായുള്ള രജിസ്റ്റർ ചെയ്ത കർഷകർ',
    'schemes.pmkisan.benefit': '3 ഗഡുക്കളായി പ്രതിവർഷം ₹6,000 നേരിട്ട് ബാങ്ക് അക്കൗണ്ടിലേക്ക്',
    'schemes.ulpin.name': 'ULPIN (ഭൂ-ആധാർ ഡിജിറ്റൽ ലാൻഡ് ഐഡി)',
    'schemes.ulpin.audience': 'ഓരോ ഭൂമിയുടെയും ഉടമസ്ഥർ',
    'schemes.ulpin.benefit': 'മാപ്പ്, ജിപിഎസ്, ഉടമസ്ഥാവകാശ രേഖകളോടെ 14-അക്ക ഡിജിറ്റൽ ഐഡി — തട്ടിപ്പുകൾ തടയുന്നു',
    'schemes.kcc.name': 'Kisan Credit Card (KCC വായ്പ)',
    'schemes.kcc.audience': 'ഭൂവുടമകൾ, പാട്ടക്കാർ, പങ്കുകൃഷിക്കാർ',
    'schemes.kcc.benefit': 'ഭൂമിയുടെ വിസ്തൃതി അനുസരിച്ച് കുറഞ്ഞ പലിശ നിരക്കിൽ (~4% പ്രാബല്യത്തിൽ) കാർഷിക വായ്പ',
    'schemes.soilhealth.name': 'Soil Health Card (സോയിൽ ഹെൽത്ത് കാർഡ്)',
    'schemes.soilhealth.audience': 'കൃഷിഭൂമിയുള്ള ഏതൊരു കർഷകനും',
    'schemes.soilhealth.benefit': 'സൗജന്യ മണ്ണ് പരിശോധന + വിള ശുപാർശ റിപ്പോർട്ട്',
    'schemes.pmfby.name': 'PMFBY (പ്രധാനമന്ത്രി ഫസൽ ബീമാ യോജന)',
    'schemes.pmfby.audience': 'ഭൂമിയിൽ കൃഷി ചെയ്യുന്ന കർഷകർ',
    'schemes.pmfby.benefit': 'വരൾച്ച, വെള്ളപ്പൊക്കം, കീടബാധ എന്നിവ മൂലമുണ്ടാകുന്ന വിളനാശത്തിന് നഷ്ടപരിഹാരം',
    'schemes.pmkusum.name': 'PM-KUSUM (സോളാർ അഗ്രികൾച്ചർ പമ്പ്)',
    'schemes.pmkusum.audience': 'നനവുള്ളതോ തരിശായതോ ആയ ഭൂമിയുള്ള കർഷകർ',
    'schemes.pmkusum.benefit': 'സോളാർ പമ്പുകൾക്ക് 60% വരെ സബ്‌സിഡി; ഉപയോഗിക്കാത്ത ഭൂമിയിൽ നിന്ന് അധിക വൈദ്യുതി വിൽക്കാം',
  },
  or: {
    'nav.home': 'ମୂଳ ପୃଷ୍ଠା',
    'nav.about': 'ବିବରଣୀ',
    'nav.features': 'ବୈଶିଷ୍ଟ୍ୟ',
    'nav.parcels': 'ମୋର ଜମି',
    'nav.requests': 'ଅନୁରୋଧ',
    'nav.profile': 'ପ୍ରୋଫାଇଲ୍',
    'nav.returnToPortal': 'ପୋର୍ଟାଲକୁ ଫେରନ୍ତୁ',
    'schemes.section.eyebrow': 'ପ୍ରତ୍ୟକ୍ଷ କୃଷକ ଲାଭ ଏବଂ ଅଧିକାର',
    'schemes.section.heading': 'ଆପଣଙ୍କ ଜମି ସହ ଜଡିତ ସରକାରୀ ଯୋଜନା',
    'schemes.section.subheading': 'ଆପଣଙ୍କ ଜମି ପାର୍ସଲ ଯାଞ୍ଚ ମାଧ୍ୟମରେ ପ୍ରତ୍ୟକ୍ଷ ସବସିଡି, କମ ସୁଧ ହାରରେ କୃଷି ଋଣ, ଫସଲ ବୀମା ଏବଂ ସୌର ଶକ୍ତି ପ୍ରୋତ୍ସାହନ ପାଆନ୍ତୁ।',
    'schemes.controls.play': 'ଚଲାନ୍ତୁ',
    'schemes.controls.pause': 'ରଖନ୍ତୁ',
    'schemes.common.learnMore': 'ଅଧିକ ଜାଣନ୍ତୁ',
    'schemes.common.forLabel': 'କାହା ପାଇଁ',
    'schemes.common.benefitLabel': 'ମୁଖ୍ୟ ଲାଭ',
    'schemes.common.officialPortal': 'ଅଫିସିଆଲ ସରକାରୀ ଯୋଜନା',
    'schemes.pmkisan.name': 'PM-KISAN (ପ୍ରଧାନମନ୍ତ୍ରୀ କିଷାନ ସମ୍ମାନ ନିଧି)',
    'schemes.pmkisan.audience': 'ପଞ୍ଜୀକୃତ ଚାଷଜମି ଥିବା କୃଷକ',
    'schemes.pmkisan.benefit': '3ଟି କିସ୍ତିରେ ବାର୍ଷିକ ₹6,000 ସିଧାସଳଖ ବ୍ୟାଙ୍କ ଟ୍ରାନ୍ସଫର',
    'schemes.ulpin.name': 'ULPIN (ଭୂ-ଆଧାର ଡିଜିଟାଲ ଜମି ଆଇଡି)',
    'schemes.ulpin.audience': 'ପ୍ରତ୍ୟେକ ଜମି ଖଣ୍ଡର ମାଲିକ',
    'schemes.ulpin.benefit': 'ମାନଚିତ୍ର, ଜିପିଏସ ଏବଂ ମାଲିକାନା ରେକର୍ଡ ସହିତ 14-ଅଙ୍କ ବିଶିଷ୍ଟ ଡିଜିଟାଲ ଆଇଡି — ଜାଲିଆତି ରୋକେ',
    'schemes.kcc.name': 'Kisan Credit Card (KCC ଋଣ)',
    'schemes.kcc.audience': 'ଜମି ମାଲିକ, ପଟ୍ଟାଦାର ଏବଂ ଭାଗଚାଷୀ',
    'schemes.kcc.benefit': 'ଜମି ଆକାର ଉପରେ ଆଧାରିତ କମ ସୁଧ (~4% ପ୍ରଭାବୀ) ବିଶିଷ୍ଟ କୃଷି ଋଣ',
    'schemes.soilhealth.name': 'Soil Health Card (ମୃତ୍ତିକା ସ୍ୱାସ୍ଥ୍ୟ କାର୍ଡ)',
    'schemes.soilhealth.audience': 'କୃଷି ଜମି ଥିବା ଯେକୌଣସି କୃଷକ',
    'schemes.soilhealth.benefit': 'ମାଗଣା ମାଟି ପରୀକ୍ଷା + ଫସଲ ପୋଷକ ତତ୍ତ୍ୱ ସୁପାରିଶ ରିପୋର୍ଟ',
    'schemes.pmfby.name': 'PMFBY (ପ୍ରଧାନମନ୍ତ୍ରୀ ଫସଲ ବୀମା ଯୋଜନା)',
    'schemes.pmfby.audience': 'ନିଜ ଜମିରେ ଫସଲ ଉତ୍ପାଦନ କରୁଥିବା କୃଷକ',
    'schemes.pmfby.benefit': 'ମରୁଡ଼ି, ବନ୍ୟା, କୁଆପଥର ବୃଷ୍ଟି କିମ୍ବା ରୋଗ ଦ୍ୱାରା ଫସଲ ନଷ୍ଟ ହେଲେ କ୍ଷତିପୂରଣ',
    'schemes.pmkusum.name': 'PM-KUSUM (ସୌର କୃଷି ପମ୍ପ ଯୋଜନା)',
    'schemes.pmkusum.audience': 'ଜଳସେଚିତ କିମ୍ବା ପଡ଼ିଆ ଜମି ଥିବା କୃଷକ',
    'schemes.pmkusum.benefit': 'ସୋଲାର ପମ୍ପ ଉପରେ 60% ପର୍ଯ୍ୟନ୍ତ ସବସିଡି; ଅବ୍ୟବହୃତ ଜମିରୁ ଅତିରିକ୍ତ ବିଦ୍ୟୁତ ବିକ୍ରି କରନ୍ତୁ',
  },
  pa: {
    'nav.home': 'ਮੁੱਖ ਪੰਨਾ',
    'nav.about': 'ਬਾਰੇ',
    'nav.features': 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    'nav.parcels': 'ਮੇਰੀ ਜ਼ਮੀਨ',
    'nav.requests': 'ਬੇਨਤੀਆਂ',
    'nav.profile': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    'nav.returnToPortal': 'ਪੋਰਟਲ ਤੇ ਵਾਪਸ ਜਾਓ',
    'schemes.section.eyebrow': 'ਸਿੱਧੇ ਕਿਸਾਨ ਲਾਭ ਅਤੇ ਅਧਿਕਾਰ',
    'schemes.section.heading': 'ਤੁਹਾਡੀ ਜ਼ਮੀਨ ਨਾਲ ਜੁੜੀਆਂ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
    'schemes.section.subheading': 'ਆਪਣੀ ਜ਼ਮੀਨ ਰਾਹੀਂ ਪ੍ਰਮਾਣਿਤ ਸਿੱਧੀ ਨਕਦ ਸਬਸਿਡੀ, ਘੱਟ ਵਿਆਜ ਵਾਲੇ ਖੇਤੀ ਕਰਜ਼ੇ, ਫਸਲ ਬੀਮਾ ਅਤੇ ਸੌਰ ਊਰਜਾ ਲਾਭ ਪ੍ਰਾਪਤ ਕਰੋ।',
    'schemes.controls.play': 'ਚਲਾਓ',
    'schemes.controls.pause': 'ਰੋਕੋ',
    'schemes.common.learnMore': 'ਹੋਰ ਜਾਣੋ',
    'schemes.common.forLabel': 'ਕਿਸਦੇ ਲਈ ਹੈ',
    'schemes.common.benefitLabel': 'ਮੁੱਖ ਲਾਭ',
    'schemes.common.officialPortal': 'ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਸਕੀਮ',
    'schemes.pmkisan.name': 'PM-KISAN (ਪ੍ਰਧਾਨ ਮੰਤਰੀ ਕਿਸਾਨ ਸੰਮਾਨ ਨਿਧੀ)',
    'schemes.pmkisan.audience': 'ਰਜਿਸਟਰਡ ਖੇਤੀਯੋਗ ਜ਼ਮੀਨ ਵਾਲੇ ਕਿਸਾਨ',
    'schemes.pmkisan.benefit': '3 ਕਿਸ਼ਤਾਂ ਵਿੱਚ ਪ੍ਰਤੀ ਸਾਲ ₹6,000 ਸਿੱਧਾ ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ',
    'schemes.ulpin.name': 'ULPIN (ਭੂ-ਆਧਾਰ ਡਿਜੀਟਲ ਲੈਂਡ ਆਈਡੀ)',
    'schemes.ulpin.audience': 'ਹਰੇਕ ਜ਼ਮੀਨ ਦੇ ਪਲਾਟ ਦਾ ਮਾਲਕ',
    'schemes.ulpin.benefit': 'ਨਕਸ਼ੇ, ਜੀਪੀਐਸ ਅਤੇ ਮਾਲਕੀ ਰਿਕਾਰਡ ਵਾਲੀ 14-ਅੰਕਾਂ ਦੀ ਡਿਜੀਟਲ ਆਈਡੀ — ਧੋਖਾਧੜੀ ਰੋਕਦੀ ਹੈ',
    'schemes.kcc.name': 'Kisan Credit Card (KCC ਕਰਜ਼ਾ)',
    'schemes.kcc.audience': 'ਜ਼ਮੀਨ ਮਾਲਕ, ਪੱਟੇਦਾਰ ਅਤੇ ਹਿੱਸੇਦਾਰ ਕਿਸਾਨ',
    'schemes.kcc.benefit': 'ਜ਼ਮੀਨ ਦੇ ਆਕਾਰ ਦੇ ਆਧਾਰ ਤੇ ਘੱਟ ਵਿਆਜ (~4% ਪ੍ਰਭਾਵੀ) ਖੇਤੀਬਾੜੀ ਕਰਜ਼ਾ',
    'schemes.soilhealth.name': 'Soil Health Card (ਮਿੱਟੀ ਸਿਹਤ ਕਾਰਡ)',
    'schemes.soilhealth.audience': 'ਖੇਤੀਬਾੜੀ ਵਾਲੀ ਜ਼ਮੀਨ ਵਾਲਾ ਕੋਈ ਵੀ ਕਿਸਾਨ',
    'schemes.soilhealth.benefit': 'ਮੁਫ਼ਤ ਮਿੱਟੀ ਦੀ ਜਾਂਚ + ਫ਼ਸਲ ਪੋਸ਼ਣ ਸੰਬੰਧੀ ਸਿਫ਼ਾਰਸ਼ ਰਿਪੋਰਟ',
    'schemes.pmfby.name': 'PMFBY (ਪ੍ਰਧਾਨ ਮੰਤਰੀ ਫਸਲ ਬੀਮਾ ਯੋਜਨਾ)',
    'schemes.pmfby.audience': 'ਆਪਣੀ ਜ਼ਮੀਨ ਤੇ ਫਸਲ ਉਗਾਉਣ ਵਾਲੇ ਕਿਸਾਨ',
    'schemes.pmfby.benefit': 'ਸੋਕਾ, ਹੜ੍ਹ, ਗੜੇਮਾਰੀ ਜਾਂ ਬਿਮਾਰੀ ਕਾਰਨ ਫਸਲ ਦੇ ਨੁਕਸਾਨ ਤੇ ਮੁਆਵਜ਼ਾ',
    'schemes.pmkusum.name': 'PM-KUSUM (ਸੋਲਰ ਖੇਤੀਬਾੜੀ ਪੰਪ)',
    'schemes.pmkusum.audience': 'ਸਿੰਚਾਈ ਵਾਲੀ ਜਾਂ ਬੰਜਰ ਜ਼ਮੀਨ ਵਾਲੇ ਕਿਸਾਨ',
    'schemes.pmkusum.benefit': 'ਸੋਲਰ ਪੰਪਾਂ ਤੇ 60% ਤੱਕ ਸਬਸਿਡੀ; ਅਣਵਰਤੀ ਜ਼ਮੀਨ ਤੋਂ ਵਾਧੂ ਬਿਜਲੀ ਵੇਚੋ',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.about': 'பற்றி',
    'nav.features': 'அம்சங்கள்',
    'nav.parcels': 'எனது நிலங்கள்',
    'nav.requests': 'கோரிக்கைகள்',
    'nav.profile': 'சுயவிவரம்',
    'nav.returnToPortal': 'போர்ட்டலுக்குத் திரும்பு',
    'schemes.section.eyebrow': 'நேரடி விவசாய நன்மைகள் மற்றும் உரிமைகள்',
    'schemes.section.heading': 'உங்கள் நிலத்துடன் இணைக்கப்பட்ட அரசு திட்டங்கள்',
    'schemes.section.subheading': 'உங்கள் நிலத்தின் மூலம் சரிபார்க்கப்பட்ட நேரடி மானியம், குறைந்த வட்டி விவசாயக் கடன், பயிர் காப்பீடு மற்றும் சூரிய ஒளி மின் திட்டங்களைப் பெறுங்கள்.',
    'schemes.controls.play': 'இயக்கு',
    'schemes.controls.pause': 'நிறுத்து',
    'schemes.common.learnMore': 'மேலும் அறிய',
    'schemes.common.forLabel': 'யாருக்கு உரியது',
    'schemes.common.benefitLabel': 'முக்கிய பலன்',
    'schemes.common.officialPortal': 'அதிகாரப்பூர்வ அரசு திட்டம்',
    'schemes.pmkisan.name': 'PM-KISAN (பிரதான் மந்திரி கிசான் சம்மான் நிதி)',
    'schemes.pmkisan.audience': 'பதிவுசெய்யப்பட்ட சாகுபடி நிலம் கொண்ட விவசாயிகள்',
    'schemes.pmkisan.benefit': '3 தவணைகளில் ஆண்டுக்கு ₹6,000 நேரடி வங்கிப் பரிமாற்றம்',
    'schemes.ulpin.name': 'ULPIN (பூ-ஆதார் டிஜிட்டல் நில ஐடி)',
    'schemes.ulpin.audience': 'ஒவ்வொரு நிலத்தின் உரிமையாளர்',
    'schemes.ulpin.benefit': 'வரைபடம், ஜிபிஎஸ் மற்றும் உரிமைப் பதிவுகளுடன் 14-இலக்க டிஜிட்டல் ஐடி — மோசடியைத் தடுக்கிறது',
    'schemes.kcc.name': 'Kisan Credit Card (KCC கடன்)',
    'schemes.kcc.audience': 'நில உரிமையாளர்கள், குத்தகைதாரர்கள் மற்றும் பங்குதாரர்கள்',
    'schemes.kcc.benefit': 'நிலத்தின் அளவிற்கு ஏற்ப குறைந்த வட்டி (~4% பயனுள்ள) விவசாயக் கடன்',
    'schemes.soilhealth.name': 'Soil Health Card (மண் வள அட்டை)',
    'schemes.soilhealth.audience': 'விவசாய நிலம் உள்ள எந்தவொரு விவசாயியும்',
    'schemes.soilhealth.benefit': 'இலவச மண் பரிசோதனை + பயிர் ஊட்டச்சத்து பரிந்துரை அறிக்கை',
    'schemes.pmfby.name': 'PMFBY (பிரதான் மந்திரி ஃபசல் பீமா யோஜனா)',
    'schemes.pmfby.audience': 'நிலத்தில் பயிர் செய்யும் விவசாயிகள்',
    'schemes.pmfby.benefit': 'வறட்சி, வெள்ளம், ஆலங்கட்டி மழை அல்லது நோயால் பயிர் சேதமடைந்தால் இழப்பீடு',
    'schemes.pmkusum.name': 'PM-KUSUM (சூரிய சக்தி விவசாய பம்ப்)',
    'schemes.pmkusum.audience': 'பாசன நிலம் அல்லது தரிசு நிலம் உள்ள விவசாயிகள்',
    'schemes.pmkusum.benefit': 'சோலார் பம்புகளுக்கு 60% வரை மானியம்; பயன்படுத்தாத நிலத்திலிருந்து கூடுதல் மின்சாரத்தை விற்கலாம்',
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.about': 'గురించి',
    'nav.features': 'ఫీచర్లు',
    'nav.parcels': 'నా భూములు',
    'nav.requests': 'అభ్యర్థనలు',
    'nav.profile': 'నా ప్రొఫైల్',
    'nav.returnToPortal': 'పోర్టల్‌కు తిరిగి వెళ్లండి',
    'schemes.section.eyebrow': 'రైతులకు ప్రత్యక్ష ప్రయోజనాలు మరియు హక్కులు',
    'schemes.section.heading': 'మీ భూమితో అనుసంధానించబడిన ప్రభుత్వ పథకాలు',
    'schemes.section.subheading': 'మీ భూమి ద్వారా ధృవీకరించబడిన ప్రత్యక్ష సబ్సిడీ, తక్కువ వడ్డీ వ్యవసాయ రుణాలు, పంట బీమా మరియు సౌర విద్యుత్ పథకాలను పొందండి.',
    'schemes.controls.play': 'ప్లే చేయండి',
    'schemes.controls.pause': 'పాజ్ చేయండి',
    'schemes.common.learnMore': 'మరింత తెలుసుకోండి',
    'schemes.common.forLabel': 'ఎవరి కోసం',
    'schemes.common.benefitLabel': 'ముఖ్య ప్రయోజనం',
    'schemes.common.officialPortal': 'అధికారిక ప్రభుత్వ పథకం',
    'schemes.pmkisan.name': 'PM-KISAN (ప్రధాన మంత్రి కిసాన్ సమ్మాన్ నిధి)',
    'schemes.pmkisan.audience': 'నమోదిత సాగు భూమి కలిగిన రైతులు',
    'schemes.pmkisan.benefit': '3 విడతల్లో సంవత్సరానికి ₹6,000 నేరుగా బ్యాంక్ బదిలీ',
    'schemes.ulpin.name': 'ULPIN (భూ-ఆధార్ డిజిటల్ ల్యాండ్ ఐడీ)',
    'schemes.ulpin.audience': 'ప్రతి భూమి యజమాని',
    'schemes.ulpin.benefit': 'మ్యాప్, జీపీఎస్ మరియు యాజమాన్య రికార్డుతో 14-అంకెల డిజిటల్ ఐడీ — మోసాలను అరికడుతుంది',
    'schemes.kcc.name': 'Kisan Credit Card (KCC రుణం)',
    'schemes.kcc.audience': 'భూ యజమానులు, కౌలుదారులు మరియు వాటాదారులు',
    'schemes.kcc.benefit': 'భూమి విస్తీర్ణం ఆధారంగా తక్కువ వడ్డీ (~4% ప్రభావవంతమైన) వ్యవసాయ రుణం',
    'schemes.soilhealth.name': 'Soil Health Card (నేల ఆరోగ్య కార్డు)',
    'schemes.soilhealth.audience': 'వ్యవసాయ భూమి ఉన్న ఏ రైతు అయినా',
    'schemes.soilhealth.benefit': 'ఉచిత నేల పరీక్ష + పంట పోషకాల సిఫార్సు నివేదిక',
    'schemes.pmfby.name': 'PMFBY (ప్రధాన మంత్రి ఫసల్ బీమా యోజన)',
    'schemes.pmfby.audience': 'తమ భూమిలో పంటలు పండించే రైతులు',
    'schemes.pmfby.benefit': 'కరువు, వరదలు, వడగండ్ల వాన లేదా తెగుళ్ల వల్ల పంట నష్టం జరిగితే పరిహారం',
    'schemes.pmkusum.name': 'PM-KUSUM (సౌర వ్యవసాయ పంప్ పథకం)',
    'schemes.pmkusum.audience': 'సాగునీటి లేదా బీడు భూమి కలిగిన రైతులు',
    'schemes.pmkusum.benefit': 'సోలార్ పంపులపై 60% వరకు సబ్సిడీ; ఉపయోగించని భూమి నుండి అదనపు విద్యుత్తును విక్రయించండి',
  },

};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [currentLang, setCurrentLang] = useState<SupportedLanguage>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored && SUPPORTED_LANGUAGES.includes(stored as SupportedLanguage)) {
        return stored as SupportedLanguage;
      }
    } catch {
      // ignore
    }
    return 'en';
  });
  const [uiText, setUiText] = useState<Record<string, string>>(() => FALLBACK_STRINGS[currentLang] || FALLBACK_STRINGS.en);
  const [loading, setLoading] = useState(false);
  const [translationFailed, setTranslationFailed] = useState(false);

  const fetchUiText = useCallback(async (lang: SupportedLanguage) => {
    setLoading(true);
    setTranslationFailed(false);
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 3500);

      const response = await fetch(`${API_BASE}/multilingual/ui-text/${lang}`, {
        signal: controller.signal,
      });
      clearTimeout(timeoutId);

      if (response.ok) {
        const data = await response.json();
        const merged = { ...(FALLBACK_STRINGS[lang] || FALLBACK_STRINGS.en), ...(data || {}) };
        setUiText(merged);
      } else {
        setUiText(FALLBACK_STRINGS[lang] || FALLBACK_STRINGS.en);
      }
    } catch (error) {
      console.warn(`Bhashini translation service fallback used for ${lang}`);
      setUiText(FALLBACK_STRINGS[lang] || FALLBACK_STRINGS.en);
      if (lang !== 'en') {
        setTranslationFailed(true);
      }
    } finally {
      setLoading(false);
    }
  }, []);

  const setLanguage = useCallback(async (lang: SupportedLanguage) => {
    if (!SUPPORTED_LANGUAGES.includes(lang)) {
      return;
    }
    setCurrentLang(lang);
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {
      // ignore
    }
    await fetchUiText(lang);
  }, [fetchUiText]);

  useEffect(() => {
    fetchUiText(currentLang);
  }, [currentLang, fetchUiText]);

  const t = useCallback((key: string, options?: Record<string, string | number> | string) => {
    let text = uiText[key] ?? (typeof options === 'string' ? options : key);
    if (options && typeof options === 'object') {
      Object.entries(options).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), String(v));
      });
    }
    return text;
  }, [uiText]);

  return (
    <LanguageContext.Provider value={{ currentLang, uiText, setLanguage, t, loading, translationFailed }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      currentLang: 'en' as SupportedLanguage,
      uiText: FALLBACK_STRINGS.en,
      setLanguage: async () => {},
      t: (key: string, options?: Record<string, string | number> | string) => {
        let text = FALLBACK_STRINGS.en[key] ?? (typeof options === 'string' ? options : key);
        if (options && typeof options === 'object') {
          Object.entries(options).forEach(([k, v]) => {
            text = text.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), String(v));
          });
        }
        return text;
      },
      loading: false,
      translationFailed: false,
    };
  }
  const { t, currentLang, setLanguage, loading, translationFailed } = context;
  return { t, currentLang, setLanguage, loading, translationFailed };
}