import {
  Search,
  FileText,
  FileCheck2,
  Building2,
  Receipt,
  ShieldAlert,
  Scale,
  Lock,
  ArrowRight,
  Layers,
  Calendar,
  TrendingUp,
  Crop,
} from 'lucide-react';

// Bilingual (EN/HI) copy for BhoomiSetuLanding.tsx and its section
// components (KNOWN_RISKS.md LOW-3 split) - kept in one place since every
// section reads from the same `content[language]` shape and the EN/HI
// objects need to stay structurally identical.
export const LANDING_CONTENT = {
  EN: {
    nav: {
      about: 'About',
      features: 'Features',
      loginRegister: 'Login / Register',
    },
    hero: {
      eyebrow: 'GIS-BASED LAND GOVERNANCE',
      headlineLine1: 'ONE PARCEL.',
      headlineLine2: 'EVERY RECORD.',
      body: 'Connecting fragmented land data into a single, verifiable view.',
      searchCta: 'Search a Parcel',
      signInCta: 'Get Started',
      badge: 'BhoomiSetu',
      footerStrip: 'GOVERNMENT OF INDIA | DIGITAL INDIA | SVAMITVA SCHEME',
    },
    stats: [
      { value: '220', label: 'PARCELS MAPPED' },
      { value: '5', label: 'PILOT STATES' },
      { value: '7', label: 'DEPARTMENT FEEDS' },
      { value: 'Live', label: 'GIS LAYERS', isLive: true },
    ],
    howItWorks: {
      eyebrow: 'HOW IT WORKS',
      heading: 'Four steps from plot to proof.',
      steps: [
        {
          num: '01',
          title: 'Search a Parcel',
          desc: 'Look up any plot by ULPIN, survey number, or local ID.',
          icon: Search,
        },
        {
          num: '02',
          title: 'View Parcel 360',
          desc: 'See ownership, departments, and records in one unified view.',
          icon: Layers,
        },
        {
          num: '03',
          title: 'Verify Documents',
          desc: 'OCR-check any land document against canonical records.',
          icon: FileCheck2,
        },
        {
          num: '04',
          title: 'File a Request',
          desc: 'Raise a workflow with any department and track it live.',
          icon: ArrowRight,
        },
      ],
    },
    gisPreview: {
      eyebrow: 'LIVE GIS PREVIEW',
      heading: 'One map. Five states. Zero ambiguity.',
      body: 'Every parcel carries a verifiable status — from clean title to active dispute. Officers and citizens see the same truth, colored the same way, in real time.',
      legend: [
        { label: 'Verified', color: '#166534' },
        { label: 'Selected', color: '#D97706' },
        { label: 'Pending', color: '#F59E0B', isDashed: true },
        { label: 'Disputed', color: '#DC2626' },
        { label: 'High-Risk', color: '#92400E' },
      ],
    },
    interoperability: {
      eyebrow: 'INTEROPERABILITY',
      heading: 'Seven department feeds. One record.',
      feeds: [
        { name: 'Land Records', icon: FileText },
        { name: 'Registration', icon: FileCheck2 },
        { name: 'Planning', icon: Building2 },
        { name: 'Tax', icon: Receipt },
        { name: 'Restriction', icon: ShieldAlert },
        { name: 'Dispute', icon: Scale },
        { name: 'Encumbrance', icon: Lock },
      ],
    },
    landAgri: {
      eyebrow: 'LAND & AGRICULTURE',
      heading: 'The land, beyond the ledger.',
      body: 'BhoomiSetu layers agricultural metadata — extent, land use, mutation history, and valuation — alongside legal records, so every parcel tells its full story.',
      snapshotBadge: 'PARCEL SNAPSHOT',
      snapshotTitle: 'Survey No. 142 — Kharif & Rabi cycles tracked since 2019.',
      metadata: [
        { label: 'Canonical extent', value: '2.31 ha', icon: Crop },
        { label: 'Land use', value: 'Double-crop agri', icon: Layers },
        { label: 'Last mutation', value: 'Mar 2024', icon: Calendar },
        { label: 'Valuation band', value: 'Tier-II', icon: TrendingUp },
      ],
    },
    closingCta: {
      heading: 'Ready to see your land, clearly?',
      body: 'Search any parcel by ULPIN, survey number, or plot number — and get a single, verifiable view in seconds.',
      searchButton: 'Search a Parcel',
      signInButton: 'Get Started',
    },
    footer: {
      desc: 'A GIS-based land governance and interoperability platform — connecting fragmented land data into a single, verifiable view.',
      platformTitle: 'Platform',
      platformLinks: ['Search a Parcel', 'Parcel 360', 'Verify Documents', 'Live Map'],
      portalsTitle: 'Portals',
      portalsLinks: ['Citizen Portal', 'Officer Portal', 'Admin Portal'],
      aboutTitle: 'About',
      aboutLinks: ['Mission', 'Pilot States', 'Interoperability', 'Contact'],
      copyright: '© 2026 BhoomiSetu • Government land governance initiative',
      privacy: 'Privacy',
      terms: 'Terms',
      accessibility: 'Accessibility',
    },
  },
  HI: {
    nav: {
      about: 'परिचय',
      features: 'विशेषताएं',
      loginRegister: 'लॉगिन / पंजीकरण करें',
    },
    hero: {
      eyebrow: 'जीआईएस-आधारित भूमि शासन',
      headlineLine1: 'एक भूखंड.',
      headlineLine2: 'प्रत्येक अभिलेख.',
      body: 'खंडित भूमि डेटा को एक एकल, सत्यापन योग्य दृश्य में जोड़ना।',
      searchCta: 'भूखंड खोजें',
      signInCta: 'शुरू करें',
      badge: 'भूमिसेतु',
      footerStrip: 'भारत सरकार | डिजिटल इंडिया | स्वामित्व योजना',
    },
    stats: [
      { value: '220', label: 'भूखंड मानचित्रित' },
      { value: '5', label: 'पायलट राज्य' },
      { value: '7', label: 'विभागीय फ़ीड्स' },
      { value: 'लाइव', label: 'जीआईएस परतें', isLive: true },
    ],
    howItWorks: {
      eyebrow: 'प्रक्रिया विवरण',
      heading: 'भूखंड से प्रमाण तक चार चरण।',
      steps: [
        {
          num: '01',
          title: 'भूखंड खोजें',
          desc: 'यूलपिन (ULPIN), सर्वेक्षण संख्या या स्थानीय आईडी द्वारा कोई भी भूखंड देखें।',
          icon: Search,
        },
        {
          num: '02',
          title: 'भूखंड 360° देखें',
          desc: 'स्वामित्व, विभाग और रिकॉर्ड एक एकीकृत दृश्य में देखें।',
          icon: Layers,
        },
        {
          num: '03',
          title: 'दस्तावेज़ सत्यापित करें',
          desc: 'प्रामाणिक रिकॉर्ड के विरुद्ध भूमि दस्तावेजों की ओसीआर जांच करें।',
          icon: FileCheck2,
        },
        {
          num: '04',
          title: 'अनुरोध दर्ज करें',
          desc: 'किसी भी विभाग के साथ कार्यप्रवाह शुरू करें और लाइव ट्रैक करें।',
          icon: ArrowRight,
        },
      ],
    },
    gisPreview: {
      eyebrow: 'लाइव जीआईएस पूर्वावलोकन',
      heading: 'एक मानचित्र। पाँच राज्य। शून्य अस्पष्टता।',
      body: 'प्रत्येक भूखंड एक सत्यापन योग्य स्थिति रखता है — स्वच्छ शीर्षक से लेकर सक्रिय विवाद तक। अधिकारी और नागरिक एक ही सत्य को वास्तविक समय में देखते हैं।',
      legend: [
        { label: 'सत्यापित', color: '#166534' },
        { label: 'चयनित', color: '#D97706' },
        { label: 'लंबित', color: '#F59E0B', isDashed: true },
        { label: 'विवादित', color: '#DC2626' },
        { label: 'उच्च-जोखिम', color: '#92400E' },
      ],
    },
    interoperability: {
      eyebrow: 'अंतर-संचालनीयता',
      heading: 'सात विभागीय फ़ीड्स। एक अभिलेख।',
      feeds: [
        { name: 'भूमि रिकॉर्ड', icon: FileText },
        { name: 'पंजीकरण', icon: FileCheck2 },
        { name: 'टाउन प्लानिंग', icon: Building2 },
        { name: 'राजस्व कर', icon: Receipt },
        { name: 'प्रतिबंध', icon: ShieldAlert },
        { name: 'विवाद', icon: Scale },
        { name: 'भार/बंधक', icon: Lock },
      ],
    },
    landAgri: {
      eyebrow: 'भूमि एवं कृषि',
      heading: 'बहीखाते से परे, भूमि की संपूर्ण जानकारी।',
      body: 'भूमिसेतु कानूनी रिकॉर्ड के साथ-साथ कृषि मेटाडेटा — क्षेत्रफल, भूमि उपयोग, म्यूटेशन इतिहास और मूल्यांकन को प्रदर्शित करता है।',
      snapshotBadge: 'भूखंड स्नैपशॉट',
      snapshotTitle: 'सर्वेक्षण सं. 142 — 2019 से खरीफ और रबी चक्र ट्रैक किए गए।',
      metadata: [
        { label: 'प्रामाणिक क्षेत्रफल', value: '2.31 हेक्टेयर', icon: Crop },
        { label: 'भूमि उपयोग', value: 'द्वि-फसली कृषि', icon: Layers },
        { label: 'अंतिम म्यूटेशन', value: 'मार्च 2024', icon: Calendar },
        { label: 'मूल्यांकन श्रेणी', value: 'टियर-II', icon: TrendingUp },
      ],
    },
    closingCta: {
      heading: 'अपनी भूमि को स्पष्ट रूप से देखने के लिए तैयार हैं?',
      body: 'यूलपिन, सर्वेक्षण संख्या, या भूखंड संख्या द्वारा खोजें — और सेकंडों में एकल, सत्यापन योग्य दृश्य प्राप्त करें।',
      searchButton: 'भूखंड खोजें',
      signInButton: 'शुरू करें',
    },
    footer: {
      desc: 'एक जीआईएस-आधारित भूमि शासन और अंतर-संचालनीयता मंच — खंडित भूमि डेटा को एक एकल, सत्यापन योग्य दृश्य में जोड़ता है।',
      platformTitle: 'मंच',
      platformLinks: ['भूखंड खोजें', 'भूखंड 360°', 'दस्तावेज़ सत्यापन', 'लाइव मानचित्र'],
      portalsTitle: 'पोर्टल',
      portalsLinks: ['नागरिक पोर्टल', 'अधिकारी पोर्टल', 'प्रशासन पोर्टल'],
      aboutTitle: 'के बारे में',
      aboutLinks: ['उद्देश्य', 'पायलट राज्य', 'अंतर-संचालनीयता', 'संपर्क'],
      copyright: '© 2026 भूमिसेतु • भारत सरकार भूमि शासन पहल',
      privacy: 'गोपनीयता',
      terms: 'नियम व शर्तें',
      accessibility: 'सुगम्यता',
    },
  },
};

export type LandingLanguage = 'EN' | 'HI';
export type LandingContent = typeof LANDING_CONTENT.EN;
