"""add unique constraint on elevation_tiles state_code district

Revision ID: 1b5a3b6280c2
Revises: 9c2e1f4a7b3d
Create Date: 2026-09-18 14:12:52.687089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 isn't auto-imported by Alembic's autogenerate even when a
# migration references geoalchemy2.types.Geometry (a known limitation) -
# imported unconditionally here so every migration touching a geometry
# column works without a manual fixup.
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b5a3b6280c2'
down_revision: Union[str, None] = '9c2e1f4a7b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_land_cover_class_code', table_name='land_cover')
    op.drop_index('ix_land_cover_class_name', table_name='land_cover')
    op.drop_index('ix_land_cover_district', table_name='land_cover')
    op.drop_index('ix_land_cover_state_code', table_name='land_cover')
    op.drop_index('ix_land_cover_year', table_name='land_cover')
    op.drop_index('land_cover_class_code_idx', table_name='land_cover')
    op.drop_index('land_cover_geometry_gist', table_name='land_cover', postgresql_using='gist')
    op.drop_index('land_cover_geometry_idx', table_name='land_cover', postgresql_using='gist')
    op.drop_index('land_cover_state_district_year_idx', table_name='land_cover')
    op.drop_table('land_cover')
    op.drop_index('ix_road_networks_district', table_name='road_networks')
    op.drop_index('ix_road_networks_road_type', table_name='road_networks')
    op.drop_index('ix_road_networks_state_code', table_name='road_networks')
    op.drop_index('road_networks_geometry_gist', table_name='road_networks', postgresql_using='gist')
    op.drop_index('road_networks_geometry_idx', table_name='road_networks', postgresql_using='gist')
    op.drop_index('road_networks_road_type_idx', table_name='road_networks')
    op.drop_index('road_networks_state_district_idx', table_name='road_networks')
    op.drop_table('road_networks')
    op.drop_index('building_footprints_confidence_idx', table_name='building_footprints')
    op.drop_index('building_footprints_geometry_gist', table_name='building_footprints', postgresql_using='gist')
    op.drop_index('building_footprints_geometry_idx', table_name='building_footprints', postgresql_using='gist')
    op.drop_index('building_footprints_state_district_idx', table_name='building_footprints')
    op.drop_index('ix_building_footprints_building_type', table_name='building_footprints')
    op.drop_index('ix_building_footprints_district', table_name='building_footprints')
    op.drop_index('ix_building_footprints_state_code', table_name='building_footprints')
    op.drop_table('building_footprints')
    op.drop_index('elevation_tiles_geometry_gist', table_name='elevation_tiles', postgresql_using='gist')
    op.drop_index('elevation_tiles_geometry_idx', table_name='elevation_tiles', postgresql_using='gist')
    op.drop_index('elevation_tiles_state_district_idx', table_name='elevation_tiles')
    op.drop_index('ix_elevation_tiles_district', table_name='elevation_tiles')
    op.drop_index('ix_elevation_tiles_state_code', table_name='elevation_tiles')
    op.drop_table('elevation_tiles')
    op.drop_index('ix_parcel_terrain_profiles_parcel_id', table_name='parcel_terrain_profiles')
    op.drop_index('parcel_terrain_profiles_parcel_id_idx', table_name='parcel_terrain_profiles')
    op.drop_table('parcel_terrain_profiles')
    op.drop_index('admin_map_notes_geom_gist', table_name='admin_map_notes', postgresql_using='gist')
    op.create_index('idx_admin_map_notes_geometry', 'admin_map_notes', ['geometry'], unique=False, postgresql_using='gist')
    op.drop_index('change_detection_events_geom_gist', table_name='change_detection_events', postgresql_using='gist')
    op.create_index('idx_change_detection_events_geometry', 'change_detection_events', ['geometry'], unique=False, postgresql_using='gist')
    op.alter_column('citizen_parcels', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'Registered'::character varying"))
    op.alter_column('citizen_parcels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('infrastructure_features_geom_gist', table_name='infrastructure_features', postgresql_using='gist')
    op.create_index('idx_infrastructure_features_geometry', 'infrastructure_features', ['geometry'], unique=False, postgresql_using='gist')
    op.drop_index('parcels_geom_gist', table_name='parcels', postgresql_using='gist')
    op.drop_index('ix_processing_jobs_idempotency', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_job_type', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_status', table_name='processing_jobs')
    op.create_unique_constraint(None, 'processing_jobs', ['idempotency_key'])
    op.drop_column('processing_jobs', 'actual_eecu')
    op.drop_column('processing_jobs', 'dataset_status')
    op.drop_column('processing_jobs', 'total_estimated_eecu')
    op.drop_index('ix_profile_fields_display_order', table_name='profile_fields')
    op.drop_index('ix_profile_fields_is_active', table_name='profile_fields')
    op.drop_index('restriction_zones_geom_gist', table_name='restriction_zones', postgresql_using='gist')
    op.create_index('idx_restriction_zones_geometry', 'restriction_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.drop_index('ix_users_district', table_name='users')
    op.drop_index('ix_users_last_activity_at', table_name='users')
    op.drop_constraint('uq_users_google_id', 'users', type_='unique')
    op.drop_column('users', 'google_picture')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'google_email_verified')
    op.drop_index('zoning_overlays_geom_gist', table_name='zoning_overlays', postgresql_using='gist')
    op.create_index('idx_zoning_overlays_geometry', 'zoning_overlays', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_zoning_overlays_geometry', table_name='zoning_overlays', postgresql_using='gist')
    op.create_index('zoning_overlays_geom_gist', 'zoning_overlays', ['geometry'], unique=False, postgresql_using='gist')
    op.add_column('users', sa.Column('google_email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_users_google_id', 'users', ['google_id'])
    op.create_index('ix_users_last_activity_at', 'users', ['last_activity_at'], unique=False)
    op.create_index('ix_users_district', 'users', ['district'], unique=False)
    op.drop_index('idx_restriction_zones_geometry', table_name='restriction_zones', postgresql_using='gist')
    op.create_index('restriction_zones_geom_gist', 'restriction_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_profile_fields_is_active', 'profile_fields', ['is_active'], unique=False)
    op.create_index('ix_profile_fields_display_order', 'profile_fields', ['display_order'], unique=False)
    op.add_column('processing_jobs', sa.Column('total_estimated_eecu', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.add_column('processing_jobs', sa.Column('dataset_status', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('processing_jobs', sa.Column('actual_eecu', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'processing_jobs', type_='unique')
    op.create_index('ix_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_index('ix_processing_jobs_job_type', 'processing_jobs', ['job_type'], unique=False)
    op.create_index('ix_processing_jobs_idempotency', 'processing_jobs', ['idempotency_key'], unique=True)
    op.create_index('parcels_geom_gist', 'parcels', ['geometry'], unique=False, postgresql_using='gist')
    op.drop_index('idx_infrastructure_features_geometry', table_name='infrastructure_features', postgresql_using='gist')
    op.create_index('infrastructure_features_geom_gist', 'infrastructure_features', ['geometry'], unique=False, postgresql_using='gist')
    op.alter_column('citizen_parcels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('citizen_parcels', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'Registered'::character varying"))
    op.drop_index('idx_change_detection_events_geometry', table_name='change_detection_events', postgresql_using='gist')
    op.create_index('change_detection_events_geom_gist', 'change_detection_events', ['geometry'], unique=False, postgresql_using='gist')
    op.drop_index('idx_admin_map_notes_geometry', table_name='admin_map_notes', postgresql_using='gist')
    op.create_index('admin_map_notes_geom_gist', 'admin_map_notes', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('parcel_terrain_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('parcel_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mean_elevation_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('min_elevation_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('max_elevation_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('elevation_range_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('mean_slope_deg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('max_slope_deg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('steep_slope_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('dominant_land_cover', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('land_cover_mix', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('nearest_road_distance_m', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('nearest_road_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('road_access_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('building_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('building_coverage_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('building_density_per_ha', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('flood_risk_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name='parcel_terrain_profiles_parcel_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='parcel_terrain_profiles_pkey'),
    sa.UniqueConstraint('parcel_id', name='parcel_terrain_profiles_parcel_id_key')
    )
    op.create_index('parcel_terrain_profiles_parcel_id_idx', 'parcel_terrain_profiles', ['parcel_id'], unique=True)
    op.create_index('ix_parcel_terrain_profiles_parcel_id', 'parcel_terrain_profiles', ['parcel_id'], unique=False)
    op.create_table('elevation_tiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('min_elevation_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('max_elevation_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('mean_elevation_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('mean_slope_deg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('max_slope_deg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('slope_histogram', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('ee_asset_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='elevation_tiles_pkey')
    )
    op.create_index('ix_elevation_tiles_state_code', 'elevation_tiles', ['state_code'], unique=False)
    op.create_index('ix_elevation_tiles_district', 'elevation_tiles', ['district'], unique=False)
    op.create_index('elevation_tiles_state_district_idx', 'elevation_tiles', ['state_code', 'district'], unique=False)
    op.create_index('elevation_tiles_geometry_idx', 'elevation_tiles', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('elevation_tiles_geometry_gist', 'elevation_tiles', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('building_footprints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('building_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('height_m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='building_footprints_pkey')
    )
    op.create_index('ix_building_footprints_state_code', 'building_footprints', ['state_code'], unique=False)
    op.create_index('ix_building_footprints_district', 'building_footprints', ['district'], unique=False)
    op.create_index('ix_building_footprints_building_type', 'building_footprints', ['building_type'], unique=False)
    op.create_index('building_footprints_state_district_idx', 'building_footprints', ['state_code', 'district'], unique=False)
    op.create_index('building_footprints_geometry_idx', 'building_footprints', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('building_footprints_geometry_gist', 'building_footprints', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('building_footprints_confidence_idx', 'building_footprints', ['confidence'], unique=False)
    op.create_table('road_networks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('road_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('osm_tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='road_networks_pkey')
    )
    op.create_index('road_networks_state_district_idx', 'road_networks', ['state_code', 'district'], unique=False)
    op.create_index('road_networks_road_type_idx', 'road_networks', ['road_type'], unique=False)
    op.create_index('road_networks_geometry_idx', 'road_networks', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('road_networks_geometry_gist', 'road_networks', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_road_networks_state_code', 'road_networks', ['state_code'], unique=False)
    op.create_index('ix_road_networks_road_type', 'road_networks', ['road_type'], unique=False)
    op.create_index('ix_road_networks_district', 'road_networks', ['district'], unique=False)
    op.create_table('land_cover',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('class_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='land_cover_pkey')
    )
    op.create_index('land_cover_state_district_year_idx', 'land_cover', ['state_code', 'district', 'year'], unique=False)
    op.create_index('land_cover_geometry_idx', 'land_cover', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('land_cover_geometry_gist', 'land_cover', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('land_cover_class_code_idx', 'land_cover', ['class_code'], unique=False)
    op.create_index('ix_land_cover_year', 'land_cover', ['year'], unique=False)
    op.create_index('ix_land_cover_state_code', 'land_cover', ['state_code'], unique=False)
    op.create_index('ix_land_cover_district', 'land_cover', ['district'], unique=False)
    op.create_index('ix_land_cover_class_name', 'land_cover', ['class_name'], unique=False)
    op.create_index('ix_land_cover_class_code', 'land_cover', ['class_code'], unique=False)
    # ### end Alembic commands ###
