"""add workflows and workflow steps

Revision ID: 2620be1ef39a
Revises: 044323afddea
Create Date: 2026-09-11 22:54:12.308365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 isn't auto-imported by Alembic's autogenerate even when a
# migration references geoalchemy2.types.Geometry (a known limitation) -
# imported unconditionally here so every migration touching a geometry
# column works without a manual fixup.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '2620be1ef39a'
down_revision: Union[str, None] = '044323afddea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.String(length=40), nullable=False),
    sa.Column('current_status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('request_details', sa.Text(), nullable=True),
    sa.Column('last_remarks', sa.Text(), nullable=True),
    sa.Column('routing_notes', sa.Text(), nullable=True),
    sa.Column('citizen_id', sa.String(), nullable=True),
    sa.Column('applicant_contact', sa.String(), nullable=True),
    sa.Column('applicant_address', sa.String(), nullable=True),
    sa.Column('verification_precheck', sa.Text(), nullable=True),
    sa.Column('evidence_file_name', sa.String(), nullable=True),
    sa.Column('evidence_file_path', sa.String(), nullable=True),
    sa.Column('evidence_mime_type', sa.String(), nullable=True),
    sa.Column('evidence_extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflows_parcel_id', 'workflows', ['parcel_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=False),
    sa.Column('assigned_role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index('ix_workflows_parcel_id', table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
