"""add admin_map_notes

Revision ID: 2f435abf10cd
Revises: ff7c6e8d9c1f
Create Date: 2026-09-11 21:28:30.134692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 isn't auto-imported by Alembic's autogenerate even when a
# migration references geoalchemy2.types.Geometry (a known limitation) -
# imported unconditionally here so every migration touching a geometry
# column works without a manual fixup.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '2f435abf10cd'
down_revision: Union[str, None] = 'ff7c6e8d9c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_map_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_map_notes_district'), 'admin_map_notes', ['district'], unique=False)
    op.create_index(op.f('ix_admin_map_notes_state_code'), 'admin_map_notes', ['state_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_map_notes_state_code'), table_name='admin_map_notes')
    op.drop_index(op.f('ix_admin_map_notes_district'), table_name='admin_map_notes')
    op.drop_table('admin_map_notes')
    # ### end Alembic commands ###
