"""Add missing survey records and proposed field changes

Revision ID: 4db0e1c409d4
Revises: 874081f71312
Create Date: 2026-09-21 23:18:52.833839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 isn't auto-imported by Alembic's autogenerate even when a
# migration references geoalchemy2.types.Geometry (a known limitation) -
# imported unconditionally here so every migration touching a geometry
# column works without a manual fixup.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4db0e1c409d4'
down_revision: Union[str, None] = '874081f71312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('survey_status', sa.String(length=20), nullable=False),
    sa.Column('survey_type', sa.String(length=30), nullable=True),
    sa.Column('measured_area_sq_m', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('original_area_sq_m', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('area_delta_sq_m', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('geometry_updated', sa.Boolean(), nullable=False),
    sa.Column('survey_date', sa.Date(), nullable=True),
    sa.Column('surveyor_notes', sa.String(length=500), nullable=True),
    sa.Column('reference_document', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_records_parcel_id'), 'survey_records', ['parcel_id'], unique=False)
    op.create_table('proposed_field_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proposed_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_field_changes_case_id'), 'proposed_field_changes', ['case_id'], unique=False)
    op.create_index('ix_proposed_field_changes_case_status', 'proposed_field_changes', ['case_id', 'status'], unique=False)
    op.create_index(op.f('ix_proposed_field_changes_department'), 'proposed_field_changes', ['department'], unique=False)
    op.create_index(op.f('ix_proposed_field_changes_parcel_id'), 'proposed_field_changes', ['parcel_id'], unique=False)
    op.drop_constraint('uq_case_parcel_version', 'case_parcel_geometry_versions', type_='unique')
    op.create_index('ix_case_parcel_geom_version', 'case_parcel_geometry_versions', ['case_id', 'parcel_id', 'version_number'], unique=True)
    op.create_foreign_key(None, 'case_parcel_geometry_versions', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.add_column('department_tasks', sa.Column('assigned_verifier_id', sa.String(), nullable=True))
    op.add_column('department_tasks', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    # op.drop_index('ix_parcels_address_trgm', table_name='parcels', postgresql_using='gin')
    # op.alter_column('road_networks', 'osm_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.add_column('verification_evidence', sa.Column('case_id', sa.UUID(), nullable=True))
    op.add_column('verification_evidence', sa.Column('task_id', sa.UUID(), nullable=True))
    op.add_column('verification_evidence', sa.Column('evidence_id', sa.String(length=30), nullable=True))
    op.add_column('verification_evidence', sa.Column('accuracy_m', sa.Float(), nullable=True))
    op.add_column('verification_evidence', sa.Column('photo_hash', sa.String(length=128), nullable=True))
    op.add_column('verification_evidence', sa.Column('sequence', sa.Integer(), nullable=True))
    op.alter_column('verification_evidence', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('verification_evidence', 'photo_file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('verification_evidence', 'photo_file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('verification_evidence', 'mime_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.create_index(op.f('ix_verification_evidence_case_id'), 'verification_evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_verification_evidence_evidence_id'), 'verification_evidence', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_verification_evidence_task_id'), 'verification_evidence', ['task_id'], unique=False)
    op.create_foreign_key(None, 'verification_evidence', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_evidence', type_='foreignkey')
    op.drop_index(op.f('ix_verification_evidence_task_id'), table_name='verification_evidence')
    op.drop_index(op.f('ix_verification_evidence_evidence_id'), table_name='verification_evidence')
    op.drop_index(op.f('ix_verification_evidence_case_id'), table_name='verification_evidence')
    op.alter_column('verification_evidence', 'mime_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('verification_evidence', 'photo_file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('verification_evidence', 'photo_file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('verification_evidence', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('verification_evidence', 'sequence')
    op.drop_column('verification_evidence', 'photo_hash')
    op.drop_column('verification_evidence', 'accuracy_m')
    op.drop_column('verification_evidence', 'evidence_id')
    op.drop_column('verification_evidence', 'task_id')
    op.drop_column('verification_evidence', 'case_id')
    # op.alter_column('road_networks', 'osm_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.create_index('ix_parcels_address_trgm', 'parcels', [sa.text("((((((COALESCE(street_address, ''::character varying)::text || ' '::text) || COALESCE(locality, ''::character varying)::text) || ' '::text) || COALESCE(landmark, ''::character varying)::text) || ' '::text) || COALESCE(pincode, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_column('department_tasks', 'assigned_at')
    op.drop_column('department_tasks', 'assigned_verifier_id')
    op.drop_constraint(None, 'case_parcel_geometry_versions', type_='foreignkey')
    op.drop_index('ix_case_parcel_geom_version', table_name='case_parcel_geometry_versions')
    op.create_unique_constraint('uq_case_parcel_version', 'case_parcel_geometry_versions', ['case_id', 'parcel_id', 'version_number'])
    op.drop_index(op.f('ix_proposed_field_changes_parcel_id'), table_name='proposed_field_changes')
    op.drop_index(op.f('ix_proposed_field_changes_department'), table_name='proposed_field_changes')
    op.drop_index('ix_proposed_field_changes_case_status', table_name='proposed_field_changes')
    op.drop_index(op.f('ix_proposed_field_changes_case_id'), table_name='proposed_field_changes')
    op.drop_table('proposed_field_changes')
    op.drop_index(op.f('ix_survey_records_parcel_id'), table_name='survey_records')
    op.drop_table('survey_records')
    # ### end Alembic commands ###
