"""add_historical_state_tables_phase7

Revision ID: 6bd7d308d74c
Revises: 4db0e1c409d4
Create Date: 2026-09-22 13:07:46.470126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 isn't auto-imported by Alembic's autogenerate even when a
# migration references geoalchemy2.types.Geometry (a known limitation) -
# imported unconditionally here so every migration touching a geometry
# column works without a manual fixup.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6bd7d308d74c'
down_revision: Union[str, None] = '4db0e1c409d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute_history_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=True),
    sa.Column('has_active_dispute', sa.Boolean(), nullable=False),
    sa.Column('dispute_type', sa.String(length=30), nullable=True),
    sa.Column('case_status', sa.String(length=20), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('resolution_summary', sa.String(length=200), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolution_reason', sa.String(length=500), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_history_records_case_id'), 'dispute_history_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_dispute_history_records_dispute_id'), 'dispute_history_records', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_dispute_history_records_parcel_id'), 'dispute_history_records', ['parcel_id'], unique=False)
    op.create_table('encumbrance_history_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('has_encumbrance', sa.Boolean(), nullable=False),
    sa.Column('encumbrance_type', sa.String(length=20), nullable=True),
    sa.Column('lender_name', sa.String(length=100), nullable=True),
    sa.Column('instrument_reference', sa.String(length=60), nullable=True),
    sa.Column('registered_date', sa.Date(), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encumbrance_history_records_case_id'), 'encumbrance_history_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_encumbrance_history_records_parcel_id'), 'encumbrance_history_records', ['parcel_id'], unique=False)
    op.create_table('registration_history_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('registration_status', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=40), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('last_transaction_type', sa.String(length=30), nullable=True),
    sa.Column('last_transaction_date', sa.Date(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_history_records_case_id'), 'registration_history_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_registration_history_records_parcel_id'), 'registration_history_records', ['parcel_id'], unique=False)
    op.create_table('restriction_history_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('has_restriction', sa.Boolean(), nullable=False),
    sa.Column('restriction_type', sa.String(length=30), nullable=True),
    sa.Column('restriction_details', sa.String(length=200), nullable=True),
    sa.Column('imposing_authority', sa.String(length=60), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restriction_history_records_case_id'), 'restriction_history_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_restriction_history_records_parcel_id'), 'restriction_history_records', ['parcel_id'], unique=False)
    op.create_table('tax_history_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('assessed_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_status', sa.String(length=20), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('market_value_reference', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('valuation_source', sa.String(length=60), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_history_records_case_id'), 'tax_history_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_tax_history_records_parcel_id'), 'tax_history_records', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_tax_history_records_year'), 'tax_history_records', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_history_records_year'), table_name='tax_history_records')
    op.drop_index(op.f('ix_tax_history_records_parcel_id'), table_name='tax_history_records')
    op.drop_index(op.f('ix_tax_history_records_case_id'), table_name='tax_history_records')
    op.drop_table('tax_history_records')
    op.drop_index(op.f('ix_restriction_history_records_parcel_id'), table_name='restriction_history_records')
    op.drop_index(op.f('ix_restriction_history_records_case_id'), table_name='restriction_history_records')
    op.drop_table('restriction_history_records')
    op.drop_index(op.f('ix_registration_history_records_parcel_id'), table_name='registration_history_records')
    op.drop_index(op.f('ix_registration_history_records_case_id'), table_name='registration_history_records')
    op.drop_table('registration_history_records')
    op.drop_index(op.f('ix_encumbrance_history_records_parcel_id'), table_name='encumbrance_history_records')
    op.drop_index(op.f('ix_encumbrance_history_records_case_id'), table_name='encumbrance_history_records')
    op.drop_table('encumbrance_history_records')
    op.drop_index(op.f('ix_dispute_history_records_parcel_id'), table_name='dispute_history_records')
    op.drop_index(op.f('ix_dispute_history_records_dispute_id'), table_name='dispute_history_records')
    op.drop_index(op.f('ix_dispute_history_records_case_id'), table_name='dispute_history_records')
    op.drop_table('dispute_history_records')
    # ### end Alembic commands ###
