"""Add Google OAuth fields to User model

Revision ID: 9b88c949a6ec
Revises: ba6302b0a394
Create Date: 2026-09-18 01:05:36.643534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 isn't auto-imported by Alembic's autogenerate even when a
# migration references geoalchemy2.types.Geometry (a known limitation) -
# imported unconditionally here so every migration touching a geometry
# column works without a manual fixup.
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b88c949a6ec'
down_revision: Union[str, None] = 'ba6302b0a394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the Google OAuth fields to the users table
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_unique_constraint('uq_users_google_id', 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_google_id', 'users', type_='unique')
    op.drop_column('users', 'google_email_verified')
    op.drop_column('users', 'google_picture')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###