"""add khata_number and crop_records for official document pdf

Revision ID: cf01cbb859fb
Revises: cf198ae4abaa
Create Date: 2026-09-16 05:39:02.618858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# geoalchemy2 isn't auto-imported by Alembic's autogenerate even when a
# migration references geoalchemy2.types.Geometry (a known limitation) -
# imported unconditionally here so every migration touching a geometry
# column works without a manual fixup.
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'cf01cbb859fb'
down_revision: Union[str, None] = 'cf198ae4abaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('agricultural_year', sa.String(length=10), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('crop_type', sa.String(length=30), nullable=False),
    sa.Column('crop_name', sa.String(length=60), nullable=False),
    sa.Column('irrigated_area_sq_m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unirrigated_area_sq_m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('irrigation_source', sa.String(length=30), nullable=True),
    sa.Column('uncultivable_area_sq_m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remark', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_records_parcel_id'), 'crop_records', ['parcel_id'], unique=False)
    op.add_column('ownership_history_records', sa.Column('khata_number', sa.String(length=20), nullable=True))
    # idx_parcels_geometry drop deliberately excluded - unrelated pre-existing
    # index that autogenerate keeps flagging, not something this migration touches.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ownership_history_records', 'khata_number')
    op.drop_index(op.f('ix_crop_records_parcel_id'), table_name='crop_records')
    op.drop_table('crop_records')
    # ### end Alembic commands ###
