"""initial schema

Revision ID: ff7c6e8d9c1f
Revises: 
Create Date: 2026-09-11 21:07:25.124619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff7c6e8d9c1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_detection_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('affected_parcel_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_detection_events_district'), 'change_detection_events', ['district'], unique=False)
    op.create_index(op.f('ix_change_detection_events_state_code'), 'change_detection_events', ['state_code'], unique=False)
    op.create_table('cluster_historical_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('bounds', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_historical_snapshots_cluster_year', 'cluster_historical_snapshots', ['cluster_id', 'year'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('dispute_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('has_active_dispute', sa.Boolean(), nullable=False),
    sa.Column('dispute_type', sa.String(length=30), nullable=True),
    sa.Column('case_status', sa.String(length=20), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('resolution_summary', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_records_parcel_id'), 'dispute_records', ['parcel_id'], unique=False)
    op.create_table('encumbrance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('has_encumbrance', sa.Boolean(), nullable=False),
    sa.Column('encumbrance_type', sa.String(length=20), nullable=True),
    sa.Column('lender_name', sa.String(length=100), nullable=True),
    sa.Column('instrument_reference', sa.String(length=60), nullable=True),
    sa.Column('registered_date', sa.Date(), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encumbrance_records_parcel_id'), 'encumbrance_records', ['parcel_id'], unique=False)
    op.create_table('governance_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_alerts_parcel_id'), 'governance_alerts', ['parcel_id'], unique=False)
    op.create_table('infrastructure_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('feature_type', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_features_district'), 'infrastructure_features', ['district'], unique=False)
    op.create_index(op.f('ix_infrastructure_features_state_code'), 'infrastructure_features', ['state_code'], unique=False)
    op.create_table('ownership_history_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('document_reference', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_history_records_parcel_id'), 'ownership_history_records', ['parcel_id'], unique=False)
    op.create_table('parcel_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(length=40), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('registration_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_documents_parcel_id'), 'parcel_documents', ['parcel_id'], unique=False)
    op.create_table('parcel_historical_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('land_use', sa.String(length=40), nullable=True),
    sa.Column('zoning_status', sa.String(length=30), nullable=True),
    sa.Column('restriction_status', sa.String(length=30), nullable=True),
    sa.Column('tax_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_historical_states_parcel_id'), 'parcel_historical_states', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_parcel_historical_states_year'), 'parcel_historical_states', ['year'], unique=False)
    op.create_table('parcel_neighbours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('neighbour_parcel_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_neighbours_parcel_id'), 'parcel_neighbours', ['parcel_id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_parcel_id', sa.String(length=50), nullable=True),
    sa.Column('cluster_id', sa.String(length=50), nullable=True),
    sa.Column('ulpin', sa.String(length=50), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('district_code', sa.String(length=20), nullable=False),
    sa.Column('local_body_code', sa.String(length=20), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_sq_m', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_cluster_id'), 'parcels', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_parcels_ulpin'), 'parcels', ['ulpin'], unique=False)
    op.create_table('planning_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('land_use', sa.String(length=20), nullable=False),
    sa.Column('zoning_classification', sa.String(length=40), nullable=False),
    sa.Column('master_plan_reference', sa.String(length=60), nullable=False),
    sa.Column('building_permission_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_records_parcel_id'), 'planning_records', ['parcel_id'], unique=False)
    op.create_table('registration_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('registration_status', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=40), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('last_transaction_type', sa.String(length=30), nullable=True),
    sa.Column('last_transaction_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_records_parcel_id'), 'registration_records', ['parcel_id'], unique=False)
    op.create_table('restriction_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('has_restriction', sa.Boolean(), nullable=False),
    sa.Column('restriction_type', sa.String(length=30), nullable=True),
    sa.Column('restriction_details', sa.String(length=200), nullable=True),
    sa.Column('imposing_authority', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restriction_records_parcel_id'), 'restriction_records', ['parcel_id'], unique=False)
    op.create_table('restriction_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('restriction_type', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('affected_parcel_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restriction_zones_district'), 'restriction_zones', ['district'], unique=False)
    op.create_index(op.f('ix_restriction_zones_state_code'), 'restriction_zones', ['state_code'], unique=False)
    op.create_table('state_a_land_records',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('survey_number', sa.String(length=50), nullable=False),
    sa.Column('subdivision_number', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('village_code', sa.String(length=30), nullable=False),
    sa.Column('area_hectares', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('record_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('ix_state_a_land_records_survey_village', 'state_a_land_records', ['survey_number', 'village_code'], unique=False)
    op.create_table('state_b_land_records',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.String(length=50), nullable=False),
    sa.Column('holder_name', sa.String(length=100), nullable=False),
    sa.Column('locality_id', sa.String(length=30), nullable=False),
    sa.Column('land_extent_sqft', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('record_category', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('ix_state_b_land_records_plot_locality', 'state_b_land_records', ['plot_id', 'locality_id'], unique=False)
    op.create_table('tax_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('assessed_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_status', sa.String(length=20), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('market_value_reference', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('valuation_source', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_records_parcel_id'), 'tax_records', ['parcel_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('pending_email', sa.String(), nullable=True),
    sa.Column('pending_mobile_number', sa.String(), nullable=True),
    sa.Column('email_otp_code_hash', sa.String(), nullable=True),
    sa.Column('email_otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('email_otp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_otp_attempts', sa.Integer(), nullable=False),
    sa.Column('sms_otp_code_hash', sa.String(), nullable=True),
    sa.Column('sms_otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('sms_otp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('sms_otp_attempts', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('government_id_number', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_table('zoning_overlays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone_type', sa.String(length=30), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('parcel_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoning_overlays_district'), 'zoning_overlays', ['district'], unique=False)
    op.create_index(op.f('ix_zoning_overlays_state_code'), 'zoning_overlays', ['state_code'], unique=False)
    op.create_table('citizen_parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_id')
    )
    op.create_index(op.f('ix_citizen_parcels_citizen_id'), 'citizen_parcels', ['citizen_id'], unique=False)
    op.create_table('parcel_identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(length=50), nullable=False),
    sa.Column('identifier_value', sa.String(length=100), nullable=False),
    sa.Column('source_state', sa.String(length=10), nullable=False),
    sa.Column('source_department', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_identifiers_identifier_type'), 'parcel_identifiers', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_parcel_identifiers_identifier_value'), 'parcel_identifiers', ['identifier_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcel_identifiers_identifier_value'), table_name='parcel_identifiers')
    op.drop_index(op.f('ix_parcel_identifiers_identifier_type'), table_name='parcel_identifiers')
    op.drop_table('parcel_identifiers')
    op.drop_index(op.f('ix_citizen_parcels_citizen_id'), table_name='citizen_parcels')
    op.drop_table('citizen_parcels')
    op.drop_index(op.f('ix_zoning_overlays_state_code'), table_name='zoning_overlays')
    op.drop_index(op.f('ix_zoning_overlays_district'), table_name='zoning_overlays')
    op.drop_table('zoning_overlays')
    op.drop_table('users')
    op.drop_index(op.f('ix_tax_records_parcel_id'), table_name='tax_records')
    op.drop_table('tax_records')
    op.drop_index('ix_state_b_land_records_plot_locality', table_name='state_b_land_records')
    op.drop_table('state_b_land_records')
    op.drop_index('ix_state_a_land_records_survey_village', table_name='state_a_land_records')
    op.drop_table('state_a_land_records')
    op.drop_index(op.f('ix_restriction_zones_state_code'), table_name='restriction_zones')
    op.drop_index(op.f('ix_restriction_zones_district'), table_name='restriction_zones')
    op.drop_table('restriction_zones')
    op.drop_index(op.f('ix_restriction_records_parcel_id'), table_name='restriction_records')
    op.drop_table('restriction_records')
    op.drop_index(op.f('ix_registration_records_parcel_id'), table_name='registration_records')
    op.drop_table('registration_records')
    op.drop_index(op.f('ix_planning_records_parcel_id'), table_name='planning_records')
    op.drop_table('planning_records')
    op.drop_index(op.f('ix_parcels_ulpin'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_cluster_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_parcel_neighbours_parcel_id'), table_name='parcel_neighbours')
    op.drop_table('parcel_neighbours')
    op.drop_index(op.f('ix_parcel_historical_states_year'), table_name='parcel_historical_states')
    op.drop_index(op.f('ix_parcel_historical_states_parcel_id'), table_name='parcel_historical_states')
    op.drop_table('parcel_historical_states')
    op.drop_index(op.f('ix_parcel_documents_parcel_id'), table_name='parcel_documents')
    op.drop_table('parcel_documents')
    op.drop_index(op.f('ix_ownership_history_records_parcel_id'), table_name='ownership_history_records')
    op.drop_table('ownership_history_records')
    op.drop_index(op.f('ix_infrastructure_features_state_code'), table_name='infrastructure_features')
    op.drop_index(op.f('ix_infrastructure_features_district'), table_name='infrastructure_features')
    op.drop_table('infrastructure_features')
    op.drop_index(op.f('ix_governance_alerts_parcel_id'), table_name='governance_alerts')
    op.drop_table('governance_alerts')
    op.drop_index(op.f('ix_encumbrance_records_parcel_id'), table_name='encumbrance_records')
    op.drop_table('encumbrance_records')
    op.drop_index(op.f('ix_dispute_records_parcel_id'), table_name='dispute_records')
    op.drop_table('dispute_records')
    op.drop_table('departments')
    op.drop_index('ix_cluster_historical_snapshots_cluster_year', table_name='cluster_historical_snapshots')
    op.drop_table('cluster_historical_snapshots')
    op.drop_index(op.f('ix_change_detection_events_state_code'), table_name='change_detection_events')
    op.drop_index(op.f('ix_change_detection_events_district'), table_name='change_detection_events')
    op.drop_table('change_detection_events')
    # ### end Alembic commands ###
